### ISSUE TITLE
Adding scan distortion in HAADF simulation process 

### ISSUE THREAD

**Issue by CGao-STEM** [abTEM/abTEM#101]
Dear Jacob,

May I ask how to add a small distortion on the scan probe positions?
What I did is as follow, but it seems not being allowed.
![image](https://github.com/abTEM/abTEM/assets/59644454/55b0379c-7275-480e-a735-351927abb8b1)
 
Thanks 
Chuang

**Comment by TomaSusi** [comment]
There's a function for adding scan noise:
https://abtem.readthedocs.io/en/latest/modules/noise.html?highlight=%22scan%20noise%22#abtem.noise.add_scan_noise
