### ISSUE TITLE
Issue with the HAADF detector

### ISSUE THREAD

**Issue by kalanadasunpriya** [abTEM/abTEM#105]
Dear abTEM team,

I’m currently working with the detectors (HAADF and BF) with Pt-doped TiO2  truncated nanoparticles.  I am using the abTEM package to simulate HAADF images and BF images in order to do a comparison with real experiments. For that, I have generated a CIF file of a TIO2 truncated supercell using VESTA software. This file is used as an input file for my code for my HAADF and BF image generations.

The issue I'm struggling with the detector is the inner and outer values of the HAADF detector. Normally in order to get a signal from a HAADF detector and inner and outer values need to be a higher value than the BF detector. Typically these values are

- BF 0 - 10 mrad
- HAADF 65 -255 mrad

These conditions can be varied based on the materials and requirements we are looking for.

This is the error I'm constantly getting with the HAADF detector.
```
Multislice:   0%|          | 0/8277 [00:00<?, ?it/s]
Scan:   0%|          | 0/4900 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[15], line 3
      1 #Creating the HAADF image 
----> 3 haadf_image_tio2_001 = S.scan(gridscan, haadf, tio2_001_potential)

File ~\Miniconda\envs\abtem\lib\site-packages\abtem\waves.py:1988, in SMatrix.scan(self, scan, detectors, potential, measurements, max_batch_probes, max_batch_expansion, pbar)
   1986 for indices, exit_probes in probe_generator:
   1987     for detector in detectors:
-> 1988         new_measurement = detector.detect(exit_probes) / potential.num_frozen_phonon_configs
   1989         scan.insert_new_measurement(measurements[detector], indices, new_measurement)
   1991 measurements = list(measurements.values())

File ~\Miniconda\envs\abtem\lib\site-packages\abtem\detect.py:389, in AnnularDetector.detect(self, waves)
    386 abs2 = get_device_function(xp, 'abs2')
    388 intensity = abs2(fft2(waves.array, overwrite_x=False))
--> 389 return self._integrate_array(intensity, waves.angular_sampling, min(waves.cutoff_scattering_angles))

File ~\Miniconda\envs\abtem\lib\site-packages\abtem\detect.py:328, in AnnularDetector._integrate_array(self, array, angular_sampling, cutoff_scattering_angle)
    324 def _integrate_array(self, array: np.ndarray, angular_sampling: Tuple[float, float],
    325                      cutoff_scattering_angle: float = None):
    327     xp = get_array_module(array)
--> 328     indices = self._get_regions(array.shape[-2:], angular_sampling, cutoff_scattering_angle)[0]
    329     indexed = array.reshape(array.shape[:-2] + (-1,))[..., indices]
    330     values = xp.sum(indexed, axis=-1)

File ~\Miniconda\envs\abtem\lib\site-packages\abtem\base_classes.py:157, in cached_method.<locals>.wrapper.<locals>.new_func(*args)
    153     cache._hits += 1
    154 else:
    155     # The method will be called and its output will be cached.
--> 157     result = func(*args)
    158     cache.insert(key, result)
    159     cache._misses += 1

File ~\Miniconda\envs\abtem\lib\site-packages\abtem\detect.py:195, in _PolarDetector._get_regions(self, gpts, angular_sampling, cutoff_scattering_angle, xp)
    192 region_labels = xp.asarray(region_labels)
    194 if np.all(region_labels == -1):
--> 195     raise RuntimeError('Zero-sized detector region.')
    197 region_indices = []
    198 for indices in self._label_to_index(region_labels):

RuntimeError: Zero-sized detector region.
```

The highest value I can reach with HAADF is **18 mrad** but my required values are higher compared to these numbers. 

So my question is how to fix this run time error. 

Also, I have attached the full code with relevant input files as well here.
[TiO2_001.zip](https://github.com/abTEM/abTEM/files/11691241/TiO2_001.zip)

Best,
Kalana Halanayake

**Comment by jacobjma** [comment]
Hi Kalana,

The issue is that your real-space sampling is far too low and thus the scattering angles required for the HAADF signal are not simulated. You can check what your maximum simulated scattering angle is through the `cutoff_scattering_angles` property. The SMatrix has to have a grid to get the maximum scattering angle, you can do this:
```
S = SMatrix(expansion_cutoff=32,
            interpolation=3,
            energy=300e3,
            semiangle_cutoff=30,
            defocus=50
           )
S.grid.match(potential)
S.cutoff_scattering_angles
```
This returns $\sim 13.1 \ \mathrm{mrad}$, i.e. you only simulate up to that angle. You can change the sampling of the potential to something like $0.03 \ \mathrm{Å/pixel}$, this will give you more than $200 \ \mathrm{mrad}$ scattering at $300 \ \mathrm{keV}$ which should be enough.

All that being said, the error message should be much better, that will be fixed in the next release.

On another note, I don't think you should precalculate the potential here. There is little speed advantage in PRISM and precalculating significantly increases memory consumption.

**Comment by kalanadasunpriya** [comment]
> Hi Kalana,
> 
> The issue is that your real-space sampling is far too low and thus the scattering angles required for the HAADF signal are not simulated. You can check what your maximum simulated scattering angle is through the `cutoff_scattering_angles` property. The SMatrix has to have a grid to get the maximum scattering angle, you can do this:
> 
> ```
> S = SMatrix(expansion_cutoff=32,
>             interpolation=3,
>             energy=300e3,
>             semiangle_cutoff=30,
>             defocus=50
>            )
> S.grid.match(potential)
> S.cutoff_scattering_angles
> ```
> 
> This returns ∼13.1 mrad, i.e. you only simulate up to that angle. You can change the sampling of the potential to something like Å0.03 Å/pixel, this will give you more than 200 mrad scattering at 300 keV which should be enough.
> 
> All that being said, the error message should be much better, that will be fixed in the next release.
> 
> On another note, I don't think you should precalculate the potential here. There is little speed advantage in PRISM and precalculating significantly increases memory consumption.

**Comment by kalanadasunpriya** [comment]
Hi,
Thanks for the advice. It really helps me. One more thing to ask about it. Is there any less computationally expensive way just to check if my code works with the above sampling optimization or not since my computer is getting a lot of memory for Scan and Multislice operations?

**Comment by jacobjma** [comment]
Hi,

You can increase the interpolation or lower the expansion_cutoff, changing those does not affect the maximum scattering angles. Once you have something that works, you can increase them to the correct value.

I am not sure why your cell is that big, could you not create a smaller unit cell with periodic boundary conditions for this sample?
