### ISSUE TITLE
Gaussian CBED Discs

### ISSUE THREAD

**Issue by EoinScope** [abTEM/abTEM#107]
I tried doing some low convergence semi angle 4D-STEM simulations and I'm getting some odd results. When I decrease the convergence semi-angle below about 3 mrad the shape of the CBED disc goes from a tophat shape to a gaussian. I'm not sure if it's a parameter I am misusing or something inherent in AbTEM. It almost looks like it is converging towards a delta function. The angular sampling is around 0.1 mras so for the 2 mrad alpha I would have expected the CBED disc to be around 20 pixels wide.

![Alpha 3 mrad](https://github.com/abTEM/abTEM/assets/39127642/7c4ddf89-3c49-4528-b06b-eeebdbedb47b)
![Alpha 2 mrad](https://github.com/abTEM/abTEM/assets/39127642/042b2294-a5e2-42c8-af35-abf432652093)
![Alpha 1 mrad](https://github.com/abTEM/abTEM/assets/39127642/fa7832db-b0c4-49b4-81ab-3a29f4f5d08e)

**Comment by TomaSusi** [comment]
Hmm… are you using aberrations, since the airy disk is not visible? Can you share the code?

**Comment by EoinScope** [comment]
I was using a C3 of -1 um in those examples. I ran it again with C3 of +5 um and got a similar result. This simulation is 20 nm thick [100] Si with and the profiles on the right are along the y-direction of the CBED disc where the x-axis is in pixels. 

Code:

```
'''Define Potential'''
potential = Potential(Si * (37, 37, 37) , sampling=0.1, slice_thickness=Si.cell[2][2]/4 , parametrization='lobato').build(pbar=True)
'''Define Detectors'''
pixelated_detector = PixelatedDetector(max_angle = 6)

angles = [4,3,2,1,0.5]

for i in tqdm(range(5)):
    
    '''Define Probe'''
    probe = Probe(energy=200e3, semiangle_cutoff=angles[i], focal_spread=0, defocus=0)
    Cs = 5e-6 * 1e10 # 1 um of spherical aberration
    probe.ctf.set_parameters({'C30': Cs})
    probe.ctf.defocus = scherzer_defocus(Cs, 200e3)
    probe.grid.match(potential)
    
    '''Propagate through Sample'''    
    pos = (potential.extent[0]/2, potential.extent[0]/2)
    probe_exit_wave = probe.multislice(positions=pos, potential=potential)
    pixelated_measurement = pixelated_detector.detect(probe_exit_wave)
    
    fig, (ax1, ax2) = plt.subplots(1,2, figsize=(9,5))
    
    fig.suptitle('Si [100] Alpha {} mrad'.format(angles[i]))
    
    ax1.imshow(pixelated_measurement, extent=[-6,6,-6,6])
    ax2.plot(pixelated_measurement[int(pixelated_measurement.shape[1]/2),:])
    
    plt.tight_layout()
    
    plt.savefig(file_path + 'Changing Convergence/5um C3/Alpha {} mrad.png'.format(angles[i]), transparent = False, facecolor = 'white')
    plt.close()

```

**Comment by jacobjma** [comment]
You can fix this by setting `rolloff=0`, or some small value. By default, there is a small softening of the aperture to avoid some numerical issues. 
```
probe = Probe(energy=200e3, semiangle_cutoff=angles[i], focal_spread=0, defocus=0, rolloff=0.)
```
I note that this is already done much more elegantly in an upcoming version.

**Comment by jacobjma** [comment]
Note that the reason the softening is so large here is due to rather small semiangle cutoffs.

**Comment by EoinScope** [comment]
Thanks, I think this has solved my issue. One thing I'll say though is that in the version of AbTEM I use, rolloff does not show up anywhere in the docstring as a key word argument for the Probe( ) function and I didn't realise it had a value assigned by default. You mentioned in the upcoming version this is dealt with more elegantly so maybe this parameter will be more obvious in that version.

**Comment by TomaSusi** [comment]
That’s fair criticism, but it is indeed explicit in the new version (which is now the default branch):
https://abtem.github.io/doc/reference/api/_autosummary/abtem.waves.Probe.html#abtem.waves.Probe
