### ISSUE TITLE
orthogonalize_cell in example folder

### ISSUE THREAD

**Issue by Schuyler-Zixiao-Shi** [abTEM/abTEM#112]
Hi Toma, 

I met some problem using the example "quick_4dstem" and "quick_stem" with the newest version of abtem (1.0.0b35).

When create the MoS2 slab using the following code:

atoms = mx2(formula='MoS2', kind='2H', a=3.18, thickness=3.19, size=(1, 1, 1), vacuum=None)
atoms.cell.lengths() 

it shows: array([3.18, 3.18, 0.  ])
and in the following code:

atoms = orthogonalize_cell(atoms)

it raises error: RuntimeError: Cell vectors must have non-zero length.

Could you spare an eye on this issue? Thank you so much,

**Comment by TomaSusi** [comment]
Hi! You have no vacuum, and you can see the cell size in z is 0. That is not a valid cell that can be orthogonalized.

Please set `vacuum=4` or some value like that and try again :)

**Comment by Schuyler-Zixiao-Shi** [comment]
That solves the problem, thank you.
