### ISSUE TITLE
 dependencies version issues 

### ISSUE THREAD

**Issue by smribet** [abTEM/abTEM#113]
Hi Toma and Jacob, 

I had two small version-related issues today, as I was updating environments to the new version of abTEM.
 
1. I had set-up an environment with python 3.8. I could install abTEM, but couldn't import the package. This syntax `list[Mapping] = []` created the error, which was fixed by upgrading to python 3.9.
2. In a different environment, I had dask ` 2022.2.1 `, which was giving me an error when I tried to `.compute()` probes (`TypeError: _build_waves() got an unexpected keyword argument 'enforce_ndim'`). Upgrading dask to `2023.7.1` fixed this. 

It'd be awesome to add these minimum versions to the requirements file, so other people don't have the same problem. 

Thanks,
Stephanie

**Comment by jacobjma** [comment]
Hi Stephanie, 

Thank you very much for the awesome detailed report.

We will now require Python 3.9; it should be about time

I removed `enforce_ndim` from that function; it is not essential. I also pinned Dask to `>=2022.12.1`.

**Comment by smribet** [comment]
Great, thanks so much!

**Comment by jacobjma** [comment]
Closing it.
