### ISSUE TITLE
How to eliminate the hole in the center of the image generated by diffraction patterns.

### ISSUE THREAD

**Issue by startingbird** [abTEM/abTEM#115]
Hi Toma,

I am currently working on the simulation of the diffraction pattern. Thank you for your work, abtem makes the simulation so easy. But now I have a problem that I don't understand: a black hole in the center of the diffraction pattern has a value of 0 in the array. I want to remove this hole, and the interpolation algorithm may solve this problem, but I am not sure whether this method is correct, so I would like to ask you how to solve this problem.

**Comment by TomaSusi** [comment]
Hello! You probably are using block_direct() to remove the direct beam? Can you please show your code?

**Comment by startingbird** [comment]
Thank you so much for your answer, I've solved the problem so far. But currently, I have a new problem, I installed the latest abtem this afternoon, the beta25 version, and it seems that this version no longer supports saving diffraction profiles as hdf5 files.

**Comment by TomaSusi** [comment]
Seems you are still using the old version of the code? We have much more features for saving files in the new version:
https://abtem.github.io/doc/intro.html

**Comment by startingbird** [comment]
Thanks so much, this URL is very helpful.
