### ISSUE TITLE
Bugs in the simulation of frozen phonons (abTEM 1.0.0beta35)

### ISSUE THREAD

**Issue by startingbird** [abTEM/abTEM#117]
Hi Toma and Jacob.

I'm reading the source code for the latest abTEM and I have to say that you guys are doing a really great job. But because the version is so new, there are still some tiny bugs.
I'm using the latest version of abTEM to run the frozen phonon model from the walkthrough (https://abtem.github.io/doc/user_guide/walkthrough/frozen_phonons.html). 
However, I got a code error when I used the following code to save the diffraction pattern.
`diffraction_patterns.crop(20).index_diffraction_spots(cell=3.945).to_dataframe()`

The error message is something like the following, which is obviously a tiny bug about array conversion in Numpy.

`TypeError                                 Traceback (most recent call last)
Cell In[67], line 1
----> 1 diffraction_patterns.crop(20).index_diffraction_spots(cell=3.945).to_dataframe()
File ~/anaconda3/envs/abtem_n/lib/python3.9/site-packages/abtem/measurements.py:2091, in DiffractionPatterns.index_diffraction_spots(self, cell, threshold, distance_threshold, min_distance, integration_radius, max_index, centering)
   2088 if self.is_lazy:
   2089     raise RuntimeError("indexing not implemented for lazy measurement")
-> 2091 hkl, intensities, positions = _index_diffraction_patterns(
   2092     self,
   2093     cell,
   2094     threshold=threshold,
   2095     distance_threshold=distance_threshold,
   2096     min_distance=min_distance,
   2097     integration_radius=integration_radius,
   2098     max_index=max_index,
   2099     centering=centering,
   2100 )
   2102 ensemble_axes_metadata = self.ensemble_axes_metadata
   2104 return IndexedDiffractionPatterns(
   2105     intensities, hkl, positions, ensemble_axes_metadata, metadata=self.metadata
   2106 )

File ~/anaconda3/envs/abtem_n/lib/python3.9/site-packages/abtem/indexing.py:302, in _index_diffraction_patterns(diffraction_patterns, cell, threshold, distance_threshold, min_distance, integration_radius, max_index, centering)
    298         intensities.append(diffraction_patterns.array[..., n, m])
    300     positions.append(k[indices][min_index])
--> 302 intensities = np.array(intensities)
    304 if intensities.size == 0:
    305     raise RuntimeError("no diffraction spots found within provided threshold")

File cupy/core/core.pyx:1188, in cupy.core.core.ndarray.__array__()

TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.`

**Comment by jacobjma** [comment]
The issue seems to be related to using a GPU, which may not be supported in the indexing algorithm. Could you try sending the diffraction patterns to CPU before running the rest of the code, as shown below? 

```
diffraction_patterns.to_cpu().crop(20).index_diffraction_spots(cell=3.945).to_dataframe()
```

If this does not work could you provide some code that will reproduce the issue?
