### ISSUE TITLE
to_tif missing tifffile package

### ISSUE THREAD

**Issue by Schuyler-Zixiao-Shi** [abTEM/abTEM#119]
Hi Toma,

I got an error called "This functionality of abTEM requires tifffile, see https://github.com/cgohlke/tifffile." when calling to_tiff to save my results, but I have the tiffile package already installed. Could you provide some hint why this problem raises? Thank you!

Take care,
Schuyler

**Comment by TomaSusi** [comment]
Dear Schuyler,

It seems likely that the package is not available in the environment where you are running _ab_TEM. Can you please try to `import tifffile` in the notebook or script you are using? If that fails, your current Python environment is not finding the package. If you're using conda, activate the correct environment and install tifffile again.

Cheers,
Toma

**Comment by Schuyler-Zixiao-Shi** [comment]
Thanks! It turns out that my environment has some problems, I re-installed the environment starting with python 3.9 and abtem, and the problem is solved.
