### ISSUE TITLE
CTF 1D profile

### ISSUE THREAD

**Issue by EthanJUCB** [abTEM/abTEM#123]
Hi Toma and Jacob,

The ctf.profiles.show doesn't correctly show the phase flipped CTF plot.  It looks identical to the plot without flipping.  The same issue happens to the Wiener-filtered plot as well.  However, the 2D CTFs (ctf.show())  and the images generated from the phase-flipped CTF look correct. 

Could you please take a look at that?  Many Thanks. 

Best 
Xi

**Comment by jacobjma** [comment]
Thank you for the report; I will fix this. The main code should work, but the profile slices use different code in order to be faster. I hope to work on this tomorrow.

**Comment by jacobjma** [comment]
I think it works now. If not reopen
