### ISSUE TITLE
Issue with normalized intensity of HAADF images

### ISSUE THREAD

**Issue by kalanadasunpriya** [abTEM/abTEM#124]
I'm Kalana from Penn State University, Department of Chemistry.
I'm simulating HAADF images for Pt-deposited TiO2 NCs. When I do simulations for different thickness samples, I notice every time Pt gives the highest intensity in HAADF images. Seems like high Z Pt gives maximum intensity for all samples.

My question is, is there any way to get HAADF images with exact intensities without normalization?

**Comment by TomaSusi** [comment]
By images you presumably mean what is being displayed by the `show()` command? That is underneath using matplotlib, so normal keywords can be used. In this instance, you can use `vmax = ` to set the maximum displayed intensity, for example. If you are displaying a set of stacked ensemble of images with `explode = True`, the `common_color_scale = True` argument also forces them to use the same intensity normalization (see https://abtem.github.io/doc/user_guide/tutorials/visualizations.html).

And, ultimately, you can always simply address the underlying numerical data via the `measurement.array`.

**Comment by kalanadasunpriya** [comment]
> By images you presumably mean what is being displayed by the `show()` command? That is underneath using matplotlib, so normal keywords can be used. In this instance, you can use `vmax = ` to set the maximum displayed intensity, for example. If you are displaying a set of stacked ensemble of images with `explode = True`, the `common_color_scale = True` argument also forces them to use the same intensity normalization (see https://abtem.github.io/doc/user_guide/tutorials/visualizations.html).
> 
> And, ultimately, you can always simply address the underlying numerical data via the `measurement.array`.

Sorry for the confusion. I run simulations using the multislice technique.

**Comment by kalanadasunpriya** [comment]
Hi,
This is the code I'm using. I am not sure how to get HAADF images with exact intensities.

**Comment by TomaSusi** [comment]
I understood you are running multislice simulations, I was talking about using the `show()` method to display the resulting measurements, as you also do in the end of your example.

Perhaps I am not quite understanding what you are asking – what precisely do you mean by “exact intensities”? Do you mean something related to a given irradiation dose? In that case you can supply that using the `poisson_noise` method, which will give the intensities a magnitude with respect to the dose.

**Comment by kalanadasunpriya** [comment]
Hi,

If I run a simulation to obtain a HAADF image for Pt-deposited TiO2 NC, the generated image is shown like this.

![Pt deposited TiO2](https://github.com/abTEM/abTEM/assets/133705862/49ab8401-4a99-4796-bbbd-88011538128d)

Suppose I do a line scan including the Pt atom on the image, I get the maximum intensity value for Pt (65535 a.u). The figure is attached here.

<img width="708" alt="Screenshot 2023-10-30 at 12 40 23 PM" src="https://github.com/abTEM/abTEM/assets/133705862/59cdcaef-3312-44ab-8029-9570bc25b687">

The same happens for all my samples which have different thicknesses. Pt gives the highest intensity value as 65535 a.u. for all.

What actually I need is the exact intensities for these samples so I can compare the Pt intensity with respect to thickness.

I don't know how to obtain HAADF images with exact intensities. (without normalization)

Sorry for the confusion.

Thanks,

**Comment by TomaSusi** [comment]
If you do a thickness ensemble, visualizing with `common_color_scale = True` as I said in the beginning should allow for quantitative comparisons. Alternatively, you can use a finite dose.

**Comment by kalanadasunpriya** [comment]
Yes, these line profiles are drawn in TIF files

**Comment by TomaSusi** [comment]
I believe my responses should be sufficient to resolve your issue. You have two options:

1. Use a thickness ensemble to create visualization with comparable contrast
2. Use a finite dose to get quantitative intensities.

And in general, the recommendation is to please use our tools for line profiles over measurements without exporting TIF files.
