### ISSUE TITLE
Merging Hyperspy bug-fix

### ISSUE THREAD

**Issue by CSSFrancis** [abTEM/abTEM#126]
@jacobjma I was wondering if there is any thing blocking the merging of the commits in the abtem-dask branch.  Specifically there are some bugfixes related to the `hyperspy` integration.

It would be good to include some of those changes into a hyperspy-bundle in the next week or so.

**Comment by jacobjma** [comment]
The dask-branch has now been merged. I am sorry that talk to you about this, I moved the hyperspy integration to this [method ](https://github.com/abTEM/abTEM/blob/b2338a44c4b76dcdbe26c8a491bfba77aaca0500/abtem/array.py#L1296C9-L1296C20) of the relatively new `ArrayObject`.

 


import abtem

probe = abtem.Probe(
    semiangle_cutoff=30, energy=100e3, extent=20, sampling=0.05, defocus=[0, 100, 200]
)

measurement = probe.build().intensity().compute()

signal = measurement.to_hyperspy()

signal

**Comment by jacobjma** [comment]
Can you link to exactly what you are referencing? `abtem-dask` is merged with `main`, so the branch is deprecated. 

I just tested, and there was an issue with the hyperspy integration, which I fixed. See this very recent [commit](https://github.com/abTEM/abTEM/commit/61771c491854a9661907877b9ca6269494e25c7f).

abTEM only has the most basic testing for HyperSpy integration; see [here](https://github.com/abTEM/abTEM/blob/main/test/test_hyperspy.py), which allows things like this to happen. I should improve this.

**Comment by jacobjma** [comment]
This should be fixed.
