### ISSUE TITLE
The example "run_STEM_MoS2.py" doesn't work.

### ISSUE THREAD

**Issue by Lynyanyu** [abTEM/abTEM#129]
The example ` run_STEM_MoS2.py` doesn't work, method ` orthogonalize_cell` has moved and no such a path as `abtem.structures.structures` in the latest version. I adjusted them, but still couldn't make it work. It raise ` RuntimeError("Cell vectors must have non-zero length.")` or ` numpy.linalg.LinAlgError: Singular matrix` in ` orthogonalize_cell()`. Please fix it.

**Comment by Lynyanyu** [comment]
In fact I found most of the examples were based on old versions, and they don't work in the latest version.

**Comment by ikkihou** [comment]
最新版看这个就行  https://abtem.readthedocs.io/en/latest/user_guide/examples/notebooks/4d-stem_quickstart.html

**Comment by jacobjma** [comment]
I am sorry that I have not addressed your issue, please put some more effort into creating an issue that I can reasonably solve, and please be polite. I am closing this, but you can open a new issue.
