### ISSUE TITLE
Incompatability with some ASE built-in structures

### ISSUE THREAD

**Issue by realitychemist** [abTEM/abTEM#132]
When attempting to simulate one of the ASE built-in structures as a test case, I found that if `periodic=False` (which is the default) when instantiating the `Atoms` object it ends up with only two lattice vectors instead of three. I believe it's always the "z" axis - `cell[2][2]` - that gets omitted. This causes abTEM to raise a RuntimeWarning when you instantiate a potential, and then a ValueError later on when you try to do something non-lazy with that potential.

Minimal code to reproduce (you can replace `consume` with any non-lazy computation on the potential):
```py
from abtem import Potential
from ase.build import bcc100
from more_itertools import consume

structure = bcc100("Fe", size=(2, 2, 2), periodic=False)  # False is the default
potential = Potential(structure, sampling=0.04)
# RuntimeWarning: invalid value encountered in scalar divide
#   slice_thickness = (thickness / n,) * int(n)
consume(potential.generate_slices())
# ValueError: cannot convert float NaN to integer
```

<summary>Here's the traceback, with irrelevant IPython stuff trimmed:</summary>
<details>

```text
C:\...\abtem\slicing.py:48: RuntimeWarning: invalid value encountered in scalar divide
  slice_thickness = (thickness / n,) * int(n)
C:\...\abtem\atoms.py:865: RuntimeWarning: invalid value encountered in scalar divide
  reps[axis] = int(1 + 2 * np.ceil(margin / atoms.cell[axis, axis]))
Traceback (most recent call last):
  ...
  File "C:\...\abtem\potentials\iam.py", line 717, in generate_slices
    sliced_atoms = self.get_sliced_atoms()
  File "C:\...\abtem\potentials\iam.py", line 688, in get_sliced_atoms
    self._sliced_atoms = self._prepare_atoms()
  File "C:\...\abtem\potentials\iam.py", line 661, in _prepare_atoms
    atoms = pad_atoms(atoms, margins=margins, directions="z")
  File "C:\...\abtem\atoms.py", line 865, in pad_atoms
    reps[axis] = int(1 + 2 * np.ceil(margin / atoms.cell[axis, axis]))
ValueError: cannot convert float NaN to integer
```
</details>

The error appears to be raised from [this line in `atoms.py`](https://github.com/abTEM/abTEM/blob/5d0f5fb3848d3240336b7cc3edd3ccb02eca506a/abtem/atoms.py#L865C4-L865C4), although the warning raised from `slicing.py` suggests this may not be the only place where this behavior of ASE's might cause an error.

I don't think I've got a full enough understanding of abTEM's architecture to suggest a fix that's not just wallpapering over the issue (i.e. just skipping the cell padding along directions without a lattice vector) but ASE does provide `atoms.cell.rank` to check how many (non-zero) lattice vectors a cell has (2 in the error case, 3 normally), presumably meant to help out with this kind of thing.

__Edit:__ After a little more testing, I found that this gets caught by `orthogonalize_cell` instead of `pad_atoms` if you try this with a potential that isn't already orthogonal, and if it gets caught there the error has custom error text ("Cell vectors must have non-zero length.").  So a simple fix might just be to raise a similar (the same?) custom error in `pad_atoms` in case the cell is already orthogonal and the call to `orthogonalize_cell` gets skipped.

**Comment by TomaSusi** [comment]
Thanks for testing this out! In this instance I think the problem is not in _ab_TEM, but in that you are creating an unphysical structure in ASE and trying to feed it to the `Potential` object. But it's a fair point that we could throw the same error here.
