### ISSUE TITLE
Scan error while using CustomScan

### ISSUE THREAD

**Issue by vbo12345** [abTEM/abTEM#134]
Hi, I am experiencing issue while using CustomScan.
First I generate scanning positions in format which is obviously wrong, but abtem.scan() performs the calculation. Issue comes when trying to do radial integration, I get an error 'numpy.ndarray' object has no atribute 'show' (For details see the part of the code).

![Custom_scan_1](https://github.com/abTEM/abTEM/assets/69189725/5f8792e7-5894-4a24-a5d1-cb21ca960aa3)

In other iteration i attempted to replicate ROI.shape and ROI.get_positions() to give same formating as ones obtained while using GridScan(). In this iteration abtem.scan() gives error "tuple index out of range".

![Custom_scan_2 1](https://github.com/abTEM/abTEM/assets/69189725/3da2d777-3c30-456d-aa32-8c31476c4537)
![Custom_scan_2 2](https://github.com/abTEM/abTEM/assets/69189725/461b3363-f47d-4192-bfa0-912731831886)
![Custom_scan_2 3](https://github.com/abTEM/abTEM/assets/69189725/549bf71e-0f96-44e8-b71f-58a869664ffd)

Are this issues fault of the code or my inability to generate good scanning positions? If you would like to reproduce the error here is the code that generated scanning positions. They were generated like this and then copy&pasted into CustomScan(potisions = (list_of positions)).

First iteration: 
![Iteration_1](https://github.com/abTEM/abTEM/assets/69189725/04cf8208-854b-474a-9f8c-93679463aa95)

Second iteration:
![Iteration_2](https://github.com/abTEM/abTEM/assets/69189725/75a4155d-5477-4f16-ab98-4d3c5a76b076)

Thank you very much for the help.

**Comment by TomaSusi** [comment]
Does the first iteration work if you remove `.compute()` and let the code calculate the results as needed?

I'm not sure what exactly your print commands are attempting to do, but certainly printing and copy-pasting is really not a good way to generate lists of scan positions. Please have a look at a Python-native way to generate arrays.

**Comment by vbo12345** [comment]
Hi, role of print was for me to use it as an reference so that I see that format of generated positions is okay.
I managed to resolve the issue by rewriting positions in array.
Also first method above works well, its just that  once calculations is finished measured intensities through measurement.integrate_radial() are not matched with the scanning positions so that has to be done manually, but it works just fine.

Thank you for the help.
