### ISSUE TITLE
Simultaneously using frozen phonons and defocus series with PRISM algorithm

### ISSUE THREAD

**Issue by edwinsupple** [abTEM/abTEM#136]
I am attempting to simulate a defocus series with frozen phonons and get the following result. Is it possible to do this with abTEM? 

```
Exception has occurred: ValueError
Dimension 1 has 10 blocks, adjust_chunks specified with 1 blocks
  File "C:\Users\...\phonon and defocus series test.py", line 30, in <module>
    flexible_measurement = s_matrix.scan(detectors=detector, ctf=ctf)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Dimension 1 has 10 blocks, adjust_chunks specified with 1 blocks
```

Here is the code I am using to simulate:
```
import abtem
import numpy as np
from ase.io import read

Si = read('./Si - mp-149 symmetrized.cif')


frozenphonon_atoms = abtem.FrozenPhonons(Si, 2, sigmas=.1)
potential = abtem.Potential(frozenphonon_atoms, gpts=512, slice_thickness=2)
s_matrix = abtem.SMatrix(
    potential=potential,
    energy=120e3,
    semiangle_cutoff=25,
    interpolation = 2
)
s_matrix.shape

detector = abtem.FlexibleAnnularDetector()
defocus = -np.linspace(0,100, 5)
ctf = abtem.CTF(Cs = 8e-6 * 1e10, defocus=defocus, energy=s_matrix.energy)

flexible_measurement = s_matrix.scan(detectors=detector, ctf=ctf)
flexible_measurement.compute()

flexible_measurement.to_zarr('./phonon_and_defocus.zarr')
```

I have tried using `disable_s_matrix_chunks = True` and in this case the simulation runs but I instead get an error that the array dimensions don't match the expected dimensions  from the axis metadata when saving the measurement `.to_zarr()`.
```
Exception has occurred: RuntimeError
number of array dimensions (5) does not match number of axis metadata items (4)
  File "C:\Users\...\phonon and defocus series test.py", line 33, in <module>
    flexible_measurement.to_zarr('./phono_and_defocus.zarr')
RuntimeError: number of array dimensions (5) does not match number of axis metadata items (4)
```

My understanding is that if this did run successfully I would save compute time vs running a simulation for each defocus step. Is this the case or should I just do a series of simulations at a single defocus using frozen phonons to get the results I want? Thanks!

**Comment by TomaSusi** [comment]
Hi and apologies for the very delayed response! It may be that SMatrix chunking and frozen phonons are not supported currently, but the `to_zarr()` function should certainly work. @jacobjma could you have a look?

**Comment by jacobjma** [comment]
This should be fixed in the latest release.
