### ISSUE TITLE
Unusual pattern when scanning a vacuum space

### ISSUE THREAD

**Issue by cablecrossover** [abTEM/abTEM#137]
In the process of investigating the free-space propagation of the electron probe, I observed an unusual pattern that appears to be an artifact. The figures below were calculated using the code also shown below.

![fig1](https://github.com/abTEM/abTEM/assets/156437917/02a7df59-fddf-4d0e-b542-3f6f7d7776d1)
Upper row: vacuum model (beam view and side view) and scan grid used for scanning
Middle row: probe intensity (in real space and reciprocal space) and the projected potential
Bottom row: virtual image from detectors of 0-6 mrad/ 0-30 mrad/ 50-200 mrad/ total sum of the diffraction pattern

I created the vacuum grid by removing atoms using the ASE module. Interestingly, all the detector regime (BF, HAADF, total sum) exhibits a similar unusual pattern. The sampling was 0.02 A/px for both potential and probe, and the nyquist sampling was used for scanning which is 0.261 A/px.

If the vacuum space is correctly defined, all potentials should have a value of zero and be identical. However, different signals are observed at each scanning position, which may be subtle enough for other atomic simulations.

It would be helpful to know if there are other factors that I may have overlooked in my investigation.

```
atoms = ase.Atoms("C",
positions=[(20.0, 20.0, 0.0)],
                  cell=[40, 40, 100], pbc=True
)
del atoms[[atom.symbol == 'C' for atom in atoms]]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
abtem.show_atoms(atoms, title="Beam view", ax=ax1)
abtem.show_atoms(atoms, legend=True, plane="xz", title="Side view", ax=ax2);
```
```
potential = abtem.Potential(atoms, sampling=0.02)

probe = abtem.Probe(
    sampling=0.02,
    energy=200e3,
    extent=20,
    C10=0,
    semiangle_cutoff=24)

probe.grid.match(potential)

grid_scan = abtem.GridScan(
    start=[10, 10],
    end=[30, 30],
    sampling=probe.aperture.nyquist_sampling,
    fractional=False,
    potential=potential,
)

detector = abtem.PixelatedDetector(max_angle=200)

measurements = probe.scan(potential, scan=grid_scan, detectors=detector)
measurements.array
measurements.compute()
```
```
stacked = abtem.stack(
    [
        measurements.integrate_radial(0, 6),
        measurements.integrate_radial(0, 30),
        measurements.integrate_radial(50, 200),
    ],
    ("0-6", "0-30", "50-200"),
)
stacked.show(explode=True, cmap="gray", cbar=True, figsize=(15, 15));
```
```
plt.figure()
plt.imshow(np.sum(measurements.array,(2,3)).T, origin='lower',cmap='gray')
plt.colorbar()
```

**Comment by jacobjma** [comment]
Thank you for the detailed report. 

The errors you show seems to be on the order of 10^-6, i.e. the accuracy of float32 (complex64). Given that, everything you show is expected as abTEM uses 32bit float.  

> It would be helpful to know if there are other factors that I may have overlooked in my investigation.

I guess, you looked over the numerical implementation.

**Comment by jacobjma** [comment]
Hi,

Toma said most of it, but I will add a little bit. 

I think this is just a floating point error issue. Everything seems to be within or close to a 1e-6 error, i.e. the (approximate) relative precision of float32 numbers. 

We could implement float64 (complex128), but I am skeptical that anyone needs this precision. GIven the many other sources of error in this type of simulation.

**Comment by cablecrossover** [comment]
Thank you for your prompt reply. As you mentioned, the numerical error seems to have originated from the Fourier transform and floating point. I agree that float64 precision is not necessary. Once again, I appreciate your assistance!
