### ISSUE TITLE
Inconsistency of the Probe generated by new version and old version

### ISSUE THREAD

**Issue by yiranlus** [abTEM/abTEM#140]
Hi,

I am trying to migrate my code to the new version. However, I found the probe generate different profiles when I use the same configuration.

The following code is for generating probe in new version:

```python
import abtem
import matplotlib.pyplot as plt

extent=20
probe = abtem.Probe(
    sampling=0.01,
    extent=extent,
    energy=80e3,
    semiangle_cutoff=20,
    defocus=200
)
intensity = probe.build().intensity().compute()

fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(8,4))
visualization = intensity.show(cbar=True, ax=ax1)
visualization.set_column_titles("probe intensity", fontsize=12)

lineprofile = intensity.interpolate_line_at_position(
    center=(extent/2, extent/2), angle=0, extent=extent
)
lineprofile.show(ax=ax2, common_scale=True);
```
and it generates

![image](https://github.com/abTEM/abTEM/assets/19369063/e73bc9d1-f0b9-42ca-90b3-f4f11a9b4fbb)

and code using abtem-legacy:

```python
import abtem
import matplotlib.pyplot as plt
probe = abtem.Probe(
    sampling=0.01,
    extent=20,
    energy=80e3,
    semiangle_cutoff=20,
    defocus=200
)

(extent_x, extent_y) = probe.extent
plot_range = 10 # Angstrom
probe_intensity = probe.build().intensity()

fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(8,4))
probe_intensity.show(ax=ax1, cmap="viridis")
lineprofile = abtem.measure.probe_profile(probe_intensity)
lineprofile.show(ax=ax2)
plt.show()
```

and it generates

![image](https://github.com/abTEM/abTEM/assets/19369063/ce8b1838-4797-41e6-8234-224415b185a6)

Can anyone explain to me why they generate different probe profile? Is this a bug or is it an update of Probe generation code ? Thanks!

**Comment by TomaSusi** [comment]
Hi, and our apologies for the delayed response! I don't think there is any bug, I believe this difference is due to changes in how aliasing at the aperture boundary is handled in the new version. Maybe @jacobjma could confirm?

**Comment by jacobjma** [comment]
Toma is right. This is better shown in reciprocal space. I am attaching the reciprocal space intensity for both versions, the first image is using the new version. We improved the algorithm for creating the probe in the new version. 

![new_version](https://github.com/abTEM/abTEM/assets/17334286/498e6d91-1d21-4091-a01b-876cee85f588)

![old_version](https://github.com/abTEM/abTEM/assets/17334286/15c0d1bf-2f42-4ee1-bd93-af7ae2c2fab6)

However, if you have a reasonable probe or if you include partial coherence, this should not make a difference.

The question is good but I think both versions of abTEM are accurate.

**Comment by yiranlus** [comment]
Thanks for your explanation a lot.
