### ISSUE TITLE
Quickstart notebooks throwing error with  1.0.4 abTEM version

### ISSUE THREAD

**Issue by utkarshp1161** [abTEM/abTEM#147]
1. quick_hrtem_and_saed.ipynb
![image](https://github.com/abTEM/abTEM/assets/52690126/d8eaf1f6-ec0e-42e9-aab3-4c33a7cb9a28)

2. quick_4d-stem.ipynb
![image](https://github.com/abTEM/abTEM/assets/52690126/37609ce4-29ab-41d4-a70e-9e392064e783)

**Comment by TomaSusi** [comment]
Apologies, the quickstart notebooks are up to date, please refer to the tutorial only until we manage to update everything. Sorry for the inconvenience!

@jacobjma, maybe we should take these down until they are updated?

**Comment by utkarshp1161** [comment]
Thank you!
