### ISSUE TITLE
Specify GPU device index

### ISSUE THREAD

**Issue by shz224** [abTEM/abTEM#153]
Hi, how can I specify which GPU card to use for the simulation? I used 'with cp.Device(1)' but it didn't work.

**Comment by TomaSusi** [comment]
Hi! This isn't something that is controlled directly by *ab*TEM, you need to look into CuPy or even CUDA documentation on how to do this.

This link might be helpful but I don't have specific knowledge on this:
https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on

What do you mean exactly by "didn't work" though? The code gave an error? It ran but used the wrong GPU?

**Comment by TomaSusi** [comment]
Good to hear, happy simulating!
