### ISSUE TITLE
Computing potential from external charge density data

### ISSUE THREAD

**Issue by leorubiola** [abTEM/abTEM#156]
Hi Jacob and Toma,

We are having an issue concerning the use of an external charge density as an input file for abTEM simulations.
The DFT density (computed with VASP) was done on an orthogonalized cell, and saved as a Gaussian cube file (.cube). We converted it into a 3D numpy array. 

We then created a `ChargeDensityPotential` object giving as arguments the atoms object of the orthogonalized cell, the charge density numpy array and the number grid points in the x,y plane. Below is a minimal working example of what we did :
```python
import abtem
import ase
from cubetools import read_cube # available at https://gist.github.com/aditya95sriram/8d1fccbb91dae93c4edf31cd6a22510f

sample = ase.io.read('/orthogonalized_cell.cif')
electronic_density,meta_axes = read_cube('/charge_density.cube')

chargedensity_potential = abtem.potentials.charge_density.ChargeDensityPotential(atoms=sample, 
                                                                                 charge_density=electronic_density,
                                                                                 gpts=(128,192)) 
potential = chargedensity_potential.build()
potential.compute()
```

Whenever the potential object it has to be transformed into a non-lazy object (with `.compute()`), the following error appears 
```
AttributeError: 'numpy.ndarray' object has no attribute 'cell'
```
as if the atoms object was transformed into a numpy array throughout the computation.

We looked up a bit the source code and weren't able to find where the issue comes from.
Do you know what went wrong ? maybe we didn't use the `ChargeDensityPotential` class as it should be.

Thank you in advance for your help.

Leo

**Comment by jacobjma** [comment]
Hi Leo,

It seems that you have identified a bug. Frankly, there is not a lot of tests implemented on the ChargeDensityPotential, so it may have broken in a recent release, without me knowing. 

You are one of the few people outside of us to use this module, if it is useful we should work on implementing some more tests. I will look into the issue, hopefully early next week.

Jacob

**Comment by jacobjma** [comment]
The issue have not been fully fixed, but in the current main branch it should be possible to run a simulation using the `ChargeDensityPotential`. You currently have to precompute it (which you would usually want to anyway). 

I show an example running a simulation with a DFT potential, using GPAW with the `GPAWPotential` and with the `ChargeDensityPotential`.

The results are not exactly identical, as using the GPAW object allows us to slightly more correctly include the core charge and core electrons together. When we just have the 3D discretized all-electron density, and have to overlay the divergent core potential, some numerical issues are bound to appear. 

These issues seems to be fairly minor, as shown below (note the $10^{-4}$ scale difference), which should decrease further when an aperture or partial coherence is included.

![image](https://github.com/abTEM/abTEM/assets/17334286/8d4e302c-dd37-4f32-b016-9119722a3031)

<details>
<summary>Code to reproduce</summary>

```python
# using main branch commit 8844d49

import abtem
from ase.build import graphene
from gpaw import GPAW

abtem.config.set({"diagnostics.progress_bar": False})

# ASE atoms setup
atoms = graphene(vacuum=2, a=2.504)
atoms[0].number = 5
atoms[1].number = 7
atoms = abtem.orthogonalize_cell(atoms)

# GPAW calculations
gpaw = GPAW(txt=None, kpts=(5, 5, 1))
atoms.calc = gpaw
atoms.get_potential_energy()
density = gpaw.get_all_electron_density()  # 24x40x40 real array

# abTEM GPAW potential
potential_gpaw = abtem.GPAWPotential(gpaw, sampling=0.04).build().compute()

# abTEM ChargeDensityPotential
potential_charge_density = abtem.ChargeDensityPotential(
    atoms, density, gpts=potential_gpaw.gpts
)

potential_charge_density = potential_charge_density.build(lazy=False)

## Run MS and show results
pw = abtem.PlaneWave(energy=80e3)

wave_gpaw = pw.multislice(potential_gpaw)
wave_charge_density = pw.multislice(potential_charge_density)

abtem.stack(
    (
        wave_gpaw,
        wave_charge_density,
        wave_gpaw - wave_charge_density,
    ),
    ("GPAWPotential", "ChargePotential", "Difference"),
).show(explode=True, cbar=True, figsize=(12, 12));
```
</details>

**Comment by leorubiola** [comment]
Hi Jacob,

Thank you very much for your answer and your help. The problem is indeed solved with the last commit : we are able to get the potential out of the charge density. 
For what we want to do it is sufficient, and the slight errors should not be a problem for the degree of precision we are aiming at. 

Thanks again !
 
Leo

**Comment by jacobjma** [comment]
Create a new issue if there are further issues.

Best, Jacob
