### ISSUE TITLE
Query re: calculating cross-sections

### ISSUE THREAD

**Issue by nravigroup** [abTEM/abTEM#157]
It has been a while since I visited the abTEM page - great to see the significant changes. I had a query regarding getting cross-section from the HAADF images. There used to be a measure.integrate_disc to get the 'cross-sections' from the HAADF column intensity. This feature is apparently removed. Is there any way to integrate column intensities to get cross-sections? I checked but did not find it.

**Comment by TomaSusi** [comment]
Hi! I think you're right that this feature was dropped in the updates; we have tools just for line profiles. Maybe it would worth adding this back in, @jacobjma.

**Comment by nravigroup** [comment]
Please let me know once you add it. Thanks.

**Comment by nravigroup** [comment]
Thanks very much. Really appreciate it.

Best regards
Ravi
