### ISSUE TITLE
get the x-axis from the interpolate_line

### ISSUE THREAD

**Issue by zwcweichen** [abTEM/abTEM#159]
How can I get the real x-axis from a lineprofile which I used interpolate_line for a filter measurements. Because I want to save the intenisty and x-axis for real space in txt file.

**Comment by zwcweichen** [comment]
![image](https://github.com/abTEM/abTEM/assets/68943346/93775348-2b8f-4e75-aeb0-3357121f6a8f)
![image](https://github.com/abTEM/abTEM/assets/68943346/d8ff5ee1-b765-4a9a-a8bb-213018ad5e90)

**Comment by TomaSusi** [comment]
I'm not sure what you mean by "real x-axis"? You want to have the length dimension in calibrated units when exporting?
