### ISSUE TITLE
Could I save/export the simulated 4d-stem dataset as a numpy array?

### ISSUE THREAD

**Issue by PhysXu** [abTEM/abTEM#160]
Hi,
I recently run some 4d-stem simulation through abtem, and want to save the simulated 4d-stem as a npy file (or other formats such as h5, etc.).
How could I process it in abtem?
Or how could I transfer the result after `measurements.compute()` to a numpy array?

**Comment by TomaSusi** [comment]
For most of our objects including `Measurements`, you can access the raw numpy data by the `.array` attribute.

If you want to save your abTEM measurements to disk for future reading by abTEM, you definitely should use the `to_zarr()` function, that is our primary way to store simulation outcomes.

If you want to keep some of the structure but move from abTEM-specific data structure to something more generic, you might also consider converting to an xarray `DataArray` (https://docs.xarray.dev/en/stable/generated/xarray.DataArray.html) via the `to_data_array()` function.

**Comment by PhysXu** [comment]
Hi, @TomaSusi ,

Thanks very much for your reply and sorry for my delayed response.

Following your suggestions, I tried the `.array` method but encountered a problem.

I did the simulation with the process in [4d-stem_quickstart](https://abtem.readthedocs.io/en/latest/user_guide/examples/notebooks/4d-stem_quickstart.html). However,  when I `.array` the measurement result, the diffraction disc became elliptical.
![image](https://github.com/user-attachments/assets/4bffbf99-399b-4e34-863c-cee6f5194ead)

I suppose it is caused by the different sampling in qx and qy, as I found the shape of (8, 14, 89, 103) for the measurements: 89 in  qx and 103 in qy.

Therefore, there maybe two solutions for this issue?
1- I need resample the numpy aray in the q-space by myself, but will it introduce some interpolation artifacts?
2- How can I set the identical qx and qy in the detector space when I do my simulation? Need I change the `sampling` in the `abtem.GridScan()`?

The following is the code my used:
```
import abtem
import as

atoms = ase.build.mx2(vacuum=2)
atoms = abtem.orthogonalize_cell(atoms)
atoms *= (3, 2, 1)
abtem.show_atoms(atoms)

potential = abtem.Potential(atoms, sampling=0.05)
probe = abtem.Probe(energy=60e3, semiangle_cutoff=30)
probe.grid.match(potential)

grid_scan = abtem.GridScan(
    start=[0, 0],
    end=[1 / 3, 1 / 2],
    sampling=probe.aperture.nyquist_sampling,
    fractional=True,
    potential=potential,
)
fig, ax = abtem.show_atoms(atoms)
grid_scan.add_to_plot(ax)

detector = abtem.PixelatedDetector()
measurements = probe.scan(potential, scan=grid_scan, detectors=detector)
measurements.compute()

measurements.crop(max_angle=210).show()

data4d = measurements.crop(max_angle=210).array
plt.imshow(data4d[1,1,:,:])
```

**Comment by TomaSusi** [comment]
Indeed, there can be different sampling in qx and qy, and thus you get a non-symmetric shape that _appears_ elliptical when simply plotting the array with `imshow`.

When defining your detector, please use 

`PixelatedDetector(resample='uniform')`

to get a uniform q-sampling. Note that the sampling of the GridScan has nothing to do with this, it controls the real-space sampling of the scan.

**Comment by PhysXu** [comment]
> Indeed, there can be different sampling in qx and qy, and thus you get a non-symmetric shape that _appears_ elliptical when simply plotting the array with `imshow`.
> 
> When defining your detector, please use
> 
> `PixelatedDetector(resample='uniform')`
> 
> to get a uniform q-sampling. Note that the sampling of the GridScan has nothing to do with this, it controls the real-space sampling of the scan.

Got it.
Thanks very much for the help from you!

**Comment by mipayne** [comment]
Hi,
I have also run into this problem with version 1.0.5 and resample='uniform' did not make the q-sampling uniform/symmetric

**Comment by TomaSusi** [comment]
Hmm... what is your cell, shape of the potential, and the sampling of your diffraction patterns that results from this?

You could also use interpolation after the measurement:
https://abtem.github.io/doc/reference/api/_autosummary/abtem.measurements.DiffractionPatterns.html#abtem.measurements.DiffractionPatterns.interpolate

**Comment by mipayne** [comment]
Thanks for the response! The cell is non-square: [95.4, 165.237, 7.1899] and the potential shape is (8,1908, 3305). The sampling of the diffraction is (0.010482180293501047, 0.006051889614147021). We found a work around by forcing the potential shape to be square by extending the cell to include vacuum with 

>` atoms.cell[0][0] = atoms.cell[1][1]`

But I just tried interpolation after the measurement and that worked great and I think is better than extending the potential into the vacuum. Attaching the notebook here in case it's useful.
[08_23_abtem_4dstem_sim-Copy1.pdf](https://github.com/user-attachments/files/16773423/08_23_abtem_4dstem_sim-Copy1.pdf)

**Comment by TomaSusi** [comment]
Right, your supercell is extremely rectangular. Is there some particular reason why it has to be 30x in both x and y, couldn't you choose different multiples that result in a square supercell? 

Extending the potential by adding vacuum is not generally a good idea as it is likely to cause artifacts. if your wavefunctions extend there.

**Comment by mipayne** [comment]
No, there's not a particular reason. I just didn't think about how it would affect the final measurement sampling. Thanks for your help!
