### ISSUE TITLE
Getting one exit wave of the probe at the center of the potential after applying HAADF detectors

### ISSUE THREAD

**Issue by Tomocrystal** [abTEM/abTEM#161]
Hello,
Can we calculate exit wave (instead radial integration) of the probe at the center of the potential after applying HADDF detectors?
before applying HADDF detectors, they are
![image](https://github.com/user-attachments/assets/005c2262-4cff-473b-90df-455cc01db571)
As the thickness increases, some intensity can appear on neighbouring positions. This transversal coherence can decrease by applying HAADF detectors. But how can I simulate it by abtem?

**Comment by TomaSusi** [comment]
Hi! I'm not sure I understand the question. You can either look at the exit wave, or you can apply a detector, those two options are mutually exclusive. Typically if you simulate a HAADF signal, you scan over the entire cell, and thus the intensity to the detector at each probe position is the resulting measurement.

**Comment by Tomocrystal** [comment]
![image](https://github.com/user-attachments/assets/96c9fdd9-4717-4d47-bbb1-fd09b9d19e6f)
I read a paper in Nature, and the author used a figure above.

**Comment by TomaSusi** [comment]
Right, those are the probe wavefunctions (or the corresponding intensities) at different depths through the potential. What you plot above from _ab_TEM, presumably calculated using the `exit_planes` keyword (https://abtem.github.io/doc/user_guide/walkthrough/multislice.html#thickness-series), seems to be exactly the same thing.
