### ISSUE TITLE
An issue after install Cupy

### ISSUE THREAD

**Issue by PhysXu** [abTEM/abTEM#163]
There is an issue after I tried to install CuPy in my virtual conda_env.
`conda install -c conda-forge cupy`
![image](https://github.com/user-attachments/assets/b48adb2b-b120-4caf-9986-73f74a314fa2)

It defaultly installs Numpy==2.1 when install CuPy.
How to avoid it?

**Comment by TomaSusi** [comment]
Uninstall CuPy, and try

‘conda install -c conda-forge cupy numpy=2.0’

**Comment by PhysXu** [comment]
Hi, @TomaSusi , thanks very much for your reply.

I have deleted the incompatible virtual env, and create a new one by the following codes:
```
conda create -n abtem_cupy anaconda
conda activate abtem_cupy
pip install abtem
conda install -c conda-forge cupy
```

The above issue does not appear.

Thanks all the same for your suggestions.

**Comment by PhysXu** [comment]
BTW, I have another question about the GPU part of abtem.

I have a NVIDIA GPU (4080 S with 16GB), and I want to use it to accelerate my simulation.

I followed the [tutorial](https://abtem.readthedocs.io/en/latest/user_guide/walkthrough/parallelization.html#using-gpus) to setup the GPUs as follows:
![image](https://github.com/user-attachments/assets/bc54c66c-fe6c-4e3e-886a-90f4b9575c0d)

However, during the simulation, I did not see that the GPU was ultilized.
![image](https://github.com/user-attachments/assets/32072202-f772-4431-82e1-91366ebd5dd8)

Is there anything wrong for the the configs. of abtem?

**Comment by TomaSusi** [comment]
Please follow me instructions exactly. You have to specify cupy AND numpy in the same conda installation command.On 27.08.2024, at 04:29, M ***@***.***> wrote:﻿
Hi, @TomaSusi , thanks very much for your reply.
I have deleted the incompatible virtual env, and create a new one by the following codes:
conda create -n abtem_cupy anaconda
conda activate abtem_cupy
pip install abtem
conda install -c conda-forge cupy

The above issue does not appear.
Thanks all the same for your suggestions.

**Comment by PhysXu** [comment]
> conda install -c conda-forge cupy numpy<2.0

Hi, @TomaSusi , thanks very much for getting your reply.

I quickly tried your instructions again as follows:

create a new virtual conda_env:
```
conda create -n abtem_env
conda activate abtem_env
conda install -c conda-forge abtem
```

However, when I run `conda install -c conda-forge cupy numpy<2.0` in the next step, it told me:
![image](https://github.com/user-attachments/assets/9d01e317-093b-43a9-983c-a487ed20720d)

**Comment by PhysXu** [comment]
Hi, @TomaSusi , a quick feedback

Only the second method works:
```
conda install -c conda-forge abtem
conda install -c conda-forge cupy numpy=1.26
```

The codes of `conda install -c conda-forge abtem cupy` will install numpy==2.x and cause problems.

However, I still do not see the high utilization of my GPU after running `measurements.compute()`

**Comment by TomaSusi** [comment]
That’s progress, good!Do you specify `device='gpu'` as instructed here?https://abtem.github.io/doc/user_guide/walkthrough/parallelization.html#using-gpusIf that is the case, please make sure CuPy detects your GPU correctly:https://docs.cupy.dev/en/stable/user_guide/basic.htmlOn 27.08.2024, at 11:26, M ***@***.***> wrote:﻿
Hi, @TomaSusi , a quick feedback
Only the second method works:
conda install -c conda-forge abtem
conda install -c conda-forge cupy numpy=1.26

The codes of conda install -c conda-forge abtem cupy will install numpy==2.x and cause problems.
However, I still do not see the high utilization of my GPU after running measurements.compute()

**Comment by PhysXu** [comment]
I have specified in my jupyterlab as follows:
![image](https://github.com/user-attachments/assets/87c0aacd-7798-4bd5-94ea-1fa4d095b87b)

**Comment by TomaSusi** [comment]
Please make sure CuPy detects the correct GPU:
https://stackoverflow.com/questions/60027446/how-to-run-python-on-gpu-with-cupy
