### ISSUE TITLE
Compatibility Issues with NumPy 2.0.1 in abtem 1.0.5 for STEM Quickstart

### ISSUE THREAD

**Issue by Nick-tyh2110** [abTEM/abTEM#164]
I download the abtem package through pip install abtem. It installs abTEM 1.0.5 and NumPy 2.0.1.

I've encountered several issues with the abtem package when using NumPy 2.0. Specifically, the code still uses the itemset method, which has been removed in NumPy 2.0. Here are the details:

This occurs in Wave function, after the calculation of FWHM.

SyntaxWarning: invalid escape sequence '\e'
  tex_label="$Z, n, \ell$",
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 5
      2 probe.grid.match(potential)
      4 print(f"defocus = {probe.aberrations.defocus} Å")
----> 5 print(f"FWHM = {probe.profiles().width().compute()} Å")

File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\abtem\waves.py:1934](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/abtem/waves.py#line=1933), in Probe.profiles(self, angle)
   1930     return intersect0, intersect1
   1932 point1 = (self.extent[0] / 2, self.extent[1] / 2)
-> 1934 measurement = self.build(point1).intensity()
   1936 point2 = point1 + np.array(
   1937     [np.cos(np.pi * angle / 180), np.sin(np.pi * angle / 180)]
   1938 )
   1939 point1, point2 = _line_intersect_rectangle(
   1940     point1, point2, (0.0, 0.0), self.extent
   1941 )

File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\abtem\waves.py:1721](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/abtem/waves.py#line=1720), in Probe.build(self, scan, max_batch, lazy)
   1695 def build(
   1696     self,
   1697     scan: Sequence | BaseScan = None,
   1698     max_batch: int | str = "auto",
   1699     lazy: bool = None,
   1700 ) -> Waves:
   1701     """
   1702     Build probe wave functions at the provided positions.
   1703 
   (...)
   1719         The built probe wave functions.
   1720     """
-> 1721     return self._validate_and_build(scan=scan, max_batch=max_batch, lazy=lazy)

File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\abtem\waves.py:1688](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/abtem/waves.py#line=1687), in Probe._validate_and_build(self, scan, max_batch, lazy, potential)
   1686     probes = self._build_waves(probe)
   1687 else:
-> 1688     probes = self._lazy_build_waves(probe, max_batch)
   1690 if squeeze:
   1691     probes = probes.squeeze(axis=(-3,))

File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\abtem\waves.py:1251](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/abtem/waves.py#line=1250), in _WavesBuilder._lazy_build_waves(waves_builder, max_batch)
   1242 chunks = waves_builder._default_ensemble_chunks + waves_builder.gpts
   1244 chunks = validate_chunks(
   1245     shape=waves_builder.ensemble_shape + waves_builder.gpts,
   1246     chunks=chunks + (-1, -1),
   1247     limit=max_batch,
   1248     dtype=waves_builder.dtype,
   1249 )
-> 1251 blocks = waves_builder.ensemble_blocks(chunks=chunks[:-2])
   1253 xp = get_array_module(waves_builder.device)
   1255 array = blocks.map_blocks(
   1256     waves_builder._build_waves,
   1257     meta=xp.array((), dtype=get_dtype(complex=True)),
   (...)
   1260     wrapped=False,
   1261 )

File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\abtem\core\ensemble.py:133](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/abtem/core/ensemble.py#line=132), in Ensemble.ensemble_blocks(self, chunks)
    122 """
    123 Split the ensemble into an array of smaller ensembles.
    124 
   (...)
    128     Block sizes along each dimension.
    129 """
    131 chunks = self._validate_ensemble_chunks(chunks)
--> 133 args = self._partition_args(chunks, lazy=True)
    135 out_symbols = tuple_range(sum(len(arg.shape) for arg in args))
    137 # assert len(out_symbols) == max(len(self.ensemble_shape), 1)

File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\abtem\waves.py:1170](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/abtem/waves.py#line=1169), in _WavesBuilder._partition_args(self, chunks, lazy)
   1168 for arg_split, ensemble in zip(self._chunk_splits(), self._ensembles.values()):
   1169     arg_chunks = chunks[slice(*arg_split)]
-> 1170     args += ensemble._partition_args(arg_chunks, lazy=lazy)
   1172 return args

File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\abtem\scan.py:272](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/abtem/scan.py#line=271), in CustomScan._partition_args(self, chunks, lazy)
    270 positions = np.empty(len(chunks[0]), dtype=object)
    271 for i, (start_chunk, chunk) in enumerate(zip((0,) + cumchunks, chunks[0])):
--> 272     positions.itemset(
    273         i, {"positions": self._positions[start_chunk : start_chunk + chunk]}
    274     )
    276 if lazy:
    277     positions = da.from_array(positions, chunks=1)

AttributeError: `itemset` was removed from the ndarray class in NumPy 2.0. Use `arr[index] = value` instead.

**Comment by TomaSusi** [comment]
Yes, numpy 2.x is not yet supported fully. We added the corresponding version recently into the requirements, but for 1.5 you should manually downgrade numpy to avoid this issue.

**Comment by Nick-tyh2110** [comment]
May i know which version of NumPy is compactible with abTEM 1.0.5 for the STEM Quickstart?

**Comment by TomaSusi** [comment]
Anything below 2.x, so 1.26 would be the latest.

**Comment by Nick-tyh2110** [comment]
Thanks for the help!
