### ISSUE TITLE
Clarify output in pretty_print_transform

### ISSUE THREAD

**Issue by Sarah-A-Stock** [abTEM/abTEM#167]
Hi, I am making some tilted structures of an orthorhombic cell using ase and getting output on strain in the orthogonalised cell with pretty_print_transform in abtem. In the tutorial (https://abtem.readthedocs.io/en/latest/user_guide/tutorials/advanced_atomic_models.html under orthogonal and periodic supercells) it says that the Euler rotation angle in pretty_print_transform states any additional rotation required to make the cell orthogonal and periodic. However for my structures (7 structures in the range 0-6mrad) the Euler y output is the same as the input angle in degrees to 3dp. So is pretty_print_transform giving the input rotation angle, or are the true rotations in the orthogonalised cell effectively double the input (input + euler y)? I get the same output regardless of the number of repetitions used. The rotation angles are so small it it difficult to tell by eye and if I rotate the structure further it becomes strained, so I hope you can clarify this a bit!

**Comment by TomaSusi** [comment]
Hi! 0-6 mrad rotations are so tiny that I am not sure if you treat those with our tools. Or, at minimum, you need to allow for hundreds or even thousands of repetitions to reach commensurability for an orthogonal cell.

However, if you say you are doing _tilted_ structures? Note that the orthogonalize_cell is meant for in-plane rotations, it cannot handle tilts of the specimen as those **CANNOT** be periodic in x-y!

**Comment by TomaSusi** [comment]
If you want to simulate small tilt angles, please use our `tilt` keyword:
https://abtem.github.io/doc/user_guide/walkthrough/multislice.html#small-angle-beam-tilt

**Comment by Sarah-A-Stock** [comment]
That's very helpful! I want to simulate small specimen tilts and was going to fall back on using a probe tilt instead if I couldn't get the structures to work out. I can see now that the orthogonalisation will not work after your explanation and checking the files I have made as many are highly strained. Thank you!

**Comment by TomaSusi** [comment]
No prob, happy abTEMing!
