### ISSUE TITLE
Camera length and angular value of the camera pixels

### ISSUE THREAD

**Issue by Tama-1997** [abTEM/abTEM#169]
Dear Jacob and Toma, 

I frequently use abTEM for my 4D STEM data simulations, and I noticed that the angular value of the camera pixel remains constant even when I change the total range of the detector (max_angle). This leads me to suspect that abTEM adjusts the camera length instead of modifying the angular value. I was wondering if there's a way to fix the camera length while allowing the angular value of the pixels to change, as I haven't found a built-in function in abTEM that enables this.

My second question concerns the convention adopted in abTEM concerning the focus plane, it's a little bit unclear while using a focused probe, whether this one focuses on the entrance surface of the structure (upper plane, indicated by U on the image attached) or the exit surface of the structure (lower plane, indicated by L on the image attached), note that, by exit surface I mean the plane that starts at (x,y)=(0,0) (lower plane, L). Same with a defocused probe, it's a bit unclear whether a positive defocus value represents the situation where the beam cross is above or below the lower plane.

![Figure 18](https://github.com/user-attachments/assets/e27385f9-cb11-498f-a0bf-544341096060)

Thank you in advance for your insights and feedback. 

Tama.

**Comment by TomaSusi** [comment]
Dear Tama,

TThe reciprocal-space sampling in abTEM is inversely proportional to the real-space extent of the potential, see:
https://abtem.github.io/doc/user_guide/appendix/antialiasing.html

Regarding the defocus, it is indeed the entrance surface as described here:
https://abtem.github.io/doc/user_guide/appendix/conventions.html

Please let us know if those pages are not sufficiently addressing the questions you have!
