### ISSUE TITLE
Vacuum scan

### ISSUE THREAD

**Issue by aowenli** [abTEM/abTEM#170]
Dear Toma and Jacob,

I am trying to simulate a vacuum scan following the scripts shown in the ptychography_00.ipynb in py4DSTEM_tutorials:
```
position_scan = PositionScan([[0,0]])
empty_potential = potential.copy()

xp = abtem.device.get_array_module(empty_potential._array)
empty_potential._array = xp.zeros_like(empty_potential._array)

vacuum_probe_01 = probe_01.scan(
    position_scan,
    pixelated_detector,
    empty_potential,
    pbar=False
)[0]

vacuum_probe_01 = vacuum_probe_01.array
vacuum_probe_01 = vacuum_probe_01[500:-500,500:-500].reshape((200,5,200,5)).sum((1,3))
vacuum_probe_01 = np.random.poisson((vacuum_probe_01 * electron_dose_per_probe_01).clip(0)).astype(np.uint64)

py4DSTEM.show(
    vacuum_probe_01,
    cmap='turbo',
    vmax=1,
    power=0.333,
    figsize=(4,4),
    ticks=False,
)
```
However, I found that it doesn't work and it might be because of the updates in the latest version of abTEM, such as no PositionScan in abtem.scan now. Could you show me how to modify the code to run a vacuum scan simulation with the abTEM 1.0.6?

**Comment by TomaSusi** [comment]
Yes, that example code is for the legacy version of abTEM. You can specify a single scan position by simply giving a numpy array as the `scan` argument. Please have a look at our walkthroughs and API documentation, starting e.g. here:
https://abtem.github.io/doc/user_guide/walkthrough/multislice.html

You should also bug the py4DSTEM folks to update their tutorials :)

**Comment by aowenli** [comment]
Thank you, Toma! I will try your suggestion!

**Comment by aowenli** [comment]
Hi Toma, I tried another method at the end. I built a probe and then got its diffraction pattern using the following line:
`diffraction_patterns_probe = probe.build().diffraction_patterns(max_angle=120)`
I wonder if this is correct for creating a CBED pattern at the vacuum position?

**Comment by TomaSusi** [comment]
Hmm... actually yes, this just builds the probe and projects it to diffraction space, so no sample potential is needed! That is actually probably the best way to do it :)

**Comment by aowenli** [comment]
Great! So I will continue to use it. Thank you!
