### ISSUE TITLE
some confusing code

### ISSUE THREAD

**Issue by tomoyo1958** [abTEM/abTEM#173]
in  iam.py, line 1131,  when def from_array_and_metadata,   we have a return value : ArrayObjectType,   i cannot find any other information about it in iam.py.

![e25f8319-0768-4693-9f8c-9b73f32510a5](https://github.com/user-attachments/assets/5a43e860-72aa-45b7-9ba6-464e181c6b45)

**Comment by TomaSusi** [comment]
That's changed a bit in the latest code, but basically this was for planned additional functionality that we didn't yet implement, you can ignore it (it will raise a `NotImplementedError` in the latest main).
