### ISSUE TITLE
Question about astimatism and astigmatism_angle

### ISSUE THREAD

**Issue by Sarah-A-Stock** [abTEM/abTEM#176]
Hi, I was looking at the documentation on how  astigmatism (C12) magnitude and astigmatism angle phi12 are calculated. Are you using FWHM of the stigmated probe or a standard deviation? Also is phi12 the angle between x axis and the astigmatism direction? Is the x axis defined as the horizontal or vertical axes in the code? 

Thanks for any answers you have for this.

**Comment by TomaSusi** [comment]
The aberrations are defined via the standard phase error series expansion (as described here https://abtem.github.io/doc/user_guide/walkthrough/contrast_transfer_function.html), and so the magnitudes are the values of the coefficients. The angle is defined in that same documentation as the arctan between `k_y` and `k_x` – note that these are wavevectors, not real-space directions! But in general yes the x axis is the horizontal axis.

**Comment by TomaSusi** [comment]
@Sarah-A-Stock did my response address your question? :)
