### ISSUE TITLE
what happens if a structure fails chunk validation?

### ISSUE THREAD

**Issue by tpchuckles** [abTEM/abTEM#178]
I have a moderately large(?) structure from molecular dynamics (hBN, 50x50x1 unit cells) and when i construct a potential from this, with a convergent probe only (works fine with parallel illumination), i get an error: " File /home/athena/.local/lib/python3.11/site-packages/abtem/core/chunks.py, line 86, in validate_chunks: elif s % c:"

I have traced this back to abtem/core/chunks.py > auto_chunks() > "if total > limit:" which decrements current_chunks down to zero. 

i don't exactly know what this chunking is doing (or what it _should_ do if size of your potential is too big). trimming my volume (which i'd prefer not to do) or reducing to float32 precision (which i'd also prefer not to do) both bypass the issue. 

I have uploaded a script and requisite files [here](https://drive.google.com/drive/folders/1PeLw2IFGoSGOv93Tu66qN8dFzEpf7Roc?usp=sharing).

**Comment by TomaSusi** [comment]
The error message is a bit cryptic but it could be an indication of running out of memory.

You are using `.compute()` for a scanned measurement of a very large potential. Are you sure it will fit in memory? If you print it before computing, what’s the total size of the Dask array?

If you use `.to_zarr()` instead, will the calculation run by writing the result to disk chunk by chunk?

**Comment by tpchuckles** [comment]
right before the "if total > limit:", i had it print total and limit. these are 13744800 and 8000000 respectively. 

the potential.shape is shape (1,5,3984,3450), so one slice of this (3984,3450) gives us the 13744800. 

but where is this 8M coming from? (if this is memory based, i Have 16 GB ram, which should be able to hold 16*1024^3 (bytes) / 128 (bit cfloats) / 8 (bits/byte) = 1B 128 bit complex floats). 

testing .to_zarr():
arr=potential.build().compute()
arr.to_zarr("testToZarr")

this works, (yields a folder of 182 MB), but then how do i run multislice from that?

both:
exit_waves = probe.multislice(potential,scan=scan).compute()
and 
exit_waves = probe.multislice(arr,scan=scan).compute()
fail with the same modulo s % c error. 

interestingly, replacing:
exit_waves = probe.multislice(potential,scan=scan).compute()
with:
exit_waves = probe.multislice(potential,scan=scan,max_batch=1).compute()
avoids the error...

**Comment by TomaSusi** [comment]
It's not only about the size of the potential: when you are doing a probe.multislice, it is propagating that probe in each pixel of the potential, and that requires much more memory. I did not mean to do `.to_zarr()` for the potential construction, but for `probe.multislice()`.

You are using abTEM in a somewhat non-standard way, which requires much more memory than usual operation. Importantly, don't seem to have any detectors defined – when you try to run a scanned measurement like that with `.compute()`, it will try to store the wavefunctions for each probe position in memory, which takes a huge amount of memory.

I suggest you look at the very last part of the wavefunctions tutorial to see how the memory of the entire measurement is evaluated (https://abtem.github.io/doc/user_guide/walkthrough/wave_functions.html) and our scan & detect tutorial for how detectors are usually included in the multislice step to reduce memory use (https://abtem.github.io/doc/user_guide/walkthrough/scan_and_detect.html#stem-simulations). For more information on Dask and chunking, our parallelization tutorial is the place to go (https://abtem.github.io/doc/user_guide/walkthrough/parallelization.html).
