### ISSUE TITLE
bloch_waves.get_kinematical_diffraction_pattern() get an error

### ISSUE THREAD

**Issue by Taimin** [abTEM/abTEM#179]
Hi,
When I am running bloch_waves.get_kinematical_diffraction_pattern(), an error popped up: 
S = self.structure_factor.calculate().flatten()[self.hkl_mask] in bloch/dynamical.py
saying calculate method does not exist. Could you check? Thanks a lot.

Best,
Taimin

**Comment by Taimin** [comment]
Seems the master branch version of abtem resolved this issue. Everythign works now.

**Comment by TomaSusi** [comment]
Thanks for checking! The Bloch-wave code is still in somewhat active development so bugs present on a particular pip release may indeed be fixed in master.
