### ISSUE TITLE
abtem.structures is missing

### ISSUE THREAD

**Issue by znekula** [abTEM/abTEM#182]
Hello, I am just starting with abtem. I am trying to run an example code, 

```
from abtem import __version__
print('current version:', __version__)

import matplotlib.pyplot as plt
from ase.io import read
from ase.build import mx2

from abtem import *
from abtem.structures import orthogonalize_cell
```

However, the `structures` module is missing. I can not find it. It is not present in the repository. I need an explanation of what it is and where to find it.

**Comment by TomaSusi** [comment]
Hi and welcome! Which example is that code from? We’ve had a so-called flat namespace for several versions already, please make sure you are running an up-to-date version and start by going through our walkthrough here:
https://abtem.github.io/doc/user_guide/walkthrough/walkthrough.html

**Comment by znekula** [comment]
Thank you. The example is from the GitHub Repository:
https://github.com/abTEM/abTEM/blob/main/examples/quickstart/quick_stem.ipynb

However, as I went through the Walkthrough, all Walkthrough codes worked correctly. So, I do not need to run the example mentioned above anymore.
