### ISSUE TITLE
Overhaul of measurement module

### ISSUE THREAD

**Issue by jacobjma** [abTEM/abTEM#30]
The current measurement module, used for finalizing simulation results, is too flexible and unsustainable to support in practice.

For example, it allows you to take slices across and reduce arbitrary axes, but I am not sure it always treats the resulting calibrations correctly. Some functions like Fourier space integration; can be done across arbitrary axes, even when it does not make sense, and when the calibrations do not match the units of the integration limits.

There are many rare but difficult to handle special cases like these, and we do not need to support them when hyperspy and xarray already do it better. 

Nonetheless, we still need to support a "post-processing" step to finish many simulations. A collection of diffraction patterns representing a 4D-STEM dataset may need to be reduced to a PACBED pattern by taking the mean over the scan axes. A collection of diffraction patterns may also represent a frozen phonon ensemble, in which case we have to take the mean along the ensemble axis.

I think the "measure" module should handle targetted simulation-related cases like these and not try to be a multi-dimensional data analysis package. We will support easy conversion to hyperspy and xarray for such tasks.

The code will be simplified by introducing strongly typed measurements and axes. I believe five different types should cover all cases.
- Images
   - Ensembles of HRTEM images
   - Ensembles of STEM images
- DiffractionPatterns
   - 4D-STEM
   - Ensembles of diffraction patterns
- LineProfiles
   - STEM linescan simulations
   - Line profiles obtained from images
- PolarMeasurements (should think of a better name)
   - DPC-STEM
   - Virtual annular detector
- SpectroscopicMeasurement
   - For future features

We should be able to assume certain things for each of these objects, for example, that the last two axes of a `DiffractionPatterns` represent the centered diffraction pattern; further axes may represent scan axes and ensemble axes, strictly in that order. 
This allows confident implementation of a selected set of methods that are guaranteed to work as expected for each measurement type.

Code duplication between classes will be avoided using a mixin pattern.

Strong typing also allows special handling of certain operations, e.g., we can now easily treat interpolation differently for diffraction patterns.

To simplify things, we will only support the same units as the rest of abTEM, this is in practice already the case. If other units are desired, they could be supported when plotting or at the conversion to a hyperspy signal.

**Comment by jacobjma** [comment]
As a bit of context the dask branch allows the following pattern.

```
atoms = read('../data/srtio3_100.cif') * (8, 8, 8)

frozen_phonons = FrozenPhonons(atoms, sigmas=.1, num_configs=10)

potential = Potential(frozen_phonons, gpts=1024, chunks=50, device='gpu')

probe = Probe(energy=80e3, semiangle_cutoff=30, device='gpu')

scan = GridScan((0,0), potential.extent, sampling=probe.ctf.nyquist_sampling*.9)

exit_waves = probe.multislice(potential, scan)

diffraction_patterns = exit_waves.diffraction_patterns()

diffraction_patterns.array
```
![grafik](https://user-images.githubusercontent.com/17334286/123616338-7b010580-d806-11eb-9bf3-6bb262473cbf.png)

The `diffraction_patterns` variable is a 5d delayed measurement, where the first axis represents phonons, the next two represent scanning and the last two the diffraction pattern. To avoid blowing up most computers when calling compute, we would at least need to reduce along the frozen phonon axis, giving a 4D-STEM dataset:
```
diffraction_patterns = diffraction_patterns.mean(0)
diffraction_patterns.array
```
![grafik](https://user-images.githubusercontent.com/17334286/123616956-11cdc200-d807-11eb-88bc-7b0fd85029d3.png)

**Comment by TomaSusi** [comment]
Sounds reasonable and I agree we shouldn't try replicate functionality that others have already implemented and are in a better place to maintain and develop.

Regarding `PolarMeasurement` – perhaps an alternative name could be `AnnularMeasurement` if BF scans would be included in 4D-STEM?

**Comment by jacobjma** [comment]
> Regarding PolarMeasurement – perhaps an alternative name could be AnnularMeasurement if BF scans would be included in 4D-STEM?

I don't think that quite covers it, an annulus is just a flat ring, but a dpc measurement will have two last axes, one representing a radial coordinate and one representing an azimuthal coordinate.

**Comment by TomaSusi** [comment]
Right... though experimentally speaking one uses segmented annuli, right? But yeah maybe that's misleading in terms of the measurement object.

**Comment by CSSFrancis** [comment]
Just to give you a reference for how `hyperspy` functions and give another option. Hyperspy it separates each measurement into either a `Signal1D` or a `Signal2D` where the rest of the axes are assumed to be navigation axes.

> The code will be simplified by introducing strongly typed measurements and axes. I believe five different types should cover all cases.
> 
> * Images
>   
>   * Ensembles of HRTEM images
>   * Ensembles of STEM images
> * DiffractionPatterns
>   
>   * 4D-STEM
>   * Ensembles of diffraction patterns
> * LineProfiles
>   
>   * STEM linescan simulations
>   * Line profiles obtained from images
> * PolarMeasurements (should think of a better name)
>   
>   * DPC-STEM
>   * Virtual annular detector
> * SpectroscopicMeasurement
>   

I don't exactly know what the dimensions for each of these signals are but (from my best guess) you could think of something like:

**Signal1D:**
* STEM linescan simulations
* Line profiles obtained from image
* Virtual annular detector
* Spectroscopic Measurements

**Signal2D:**
* DPC-STEM
* Ensembles of diffraction patterns
* Ensembles of HRTEM images
* Ensembles of STEM images

This seems to work fairly well. For the most part you want to apply some function to either the navigation axis or the signal axis and rarely to both at the same time.  For example if you want to convolve the dataset in x ,y to simulate probe coherence that only operates on the navigation axes.

 If you want to add Poisson noise you might want to add noise signal wise. 

For segmented annual detector we have a `PolarDiffraction` class which is just a polar unwrapped pixelated detector but that might work for that case. 

https://github.com/pyxem/pyxem/blob/master/pyxem/signals/polar_diffraction2d.py

**Comment by jacobjma** [comment]
Thanks, hyperspy was the main inspiration when I thought about the system presented above. Measurements could be separated into 1d and 2d. However, there are differences in how to treat certain operations with diffraction patterns and images. I think a strict separation will be easier to implement. 

The clincher for me is that having a separation allows us to _not_ implement a system for units, as we will already know the units of a `DiffractionPatterns`, whereas a Signal2D can be anything.

**Comment by GearoidM** [comment]
Dear abTEM authors, 

I'm wondering if you have an update to this post. Is the dask branch in a state suitable for beta testing? I have some projects that require a good bit of memory, so I would certainly like to give the dask branch a go. 

Best wishes.

Gearóid.

**Comment by jacobjma** [comment]
@GearoidM Sorry, I missed your post. It should be ready for testing now. Hope you give it a try.
