### ISSUE TITLE
Thickness series

### ISSUE THREAD

**Issue by kotabata** [abTEM/abTEM#68]
Dear abTEM maintainer,

I would like to use a STEM multislice simulation with a thickness series. How can I obtain STEM images of different thicknesses?

Since the return value of `probe.scan()` is limited to the thickness of the supercell, it would be nice if I could get an image for each thickness by specifying the thickness series as an argument.

**Comment by jacobjma** [comment]
Sorry about the late reply. I somehow missed this issue. I am aware that creating thickness series in abTEM is too difficult, in the near future it will be much easier. However, It is possible to create thickness series right now, see the examples below

https://github.com/jacobjma/abTEM/blob/master/examples/other/pacbed_thickness_series.ipynb
https://github.com/jacobjma/abTEM/blob/master/examples/other/pacbed_thickness_series_no_prism.ipynb
https://github.com/jacobjma/abTEM/blob/master/examples/other/hrtem_thickness_series.ipynb

If these examples do not cover your problems, please let us know. We can create another example for you

**Comment by kotabata** [comment]
Thank you for your reply. I find adding thickness series method is difficult too. I will  　refer to the code and think about it.
