### ISSUE TITLE
`stack_measurements` fails when `calibrations` are a list

### ISSUE THREAD

**Issue by sezelt** [abTEM/abTEM#74]
In reductions applied to `Measurement` objects (and I think a few other places as well, e.g. [here](https://github.com/jacobjma/abTEM/blob/c6922de07c2b23823d2a4bd0a64558fcebfaf740/abtem/measure.py#L261)), calibrations are stored as a Python list:
https://github.com/jacobjma/abTEM/blob/c6922de07c2b23823d2a4bd0a64558fcebfaf740/abtem/measure.py#L422

This causes an error if you later try to use `stack_measurements` with some reduced `Measurement`s as inputs, which tries to add the list to the tuple `(None,)`:
https://github.com/jacobjma/abTEM/blob/c6922de07c2b23823d2a4bd0a64558fcebfaf740/abtem/measure.py#L1068

**Comment by jacobjma** [comment]
Thank you for finding these bugs. I think the cases you found are fixed in the latest commit?
