### ISSUE TITLE
issue on image simulation.

### ISSUE THREAD

**Issue by yc9690** [abTEM/abTEM#77]
Hello. I simulated a STEM image by using a SrTiO3 supercell with partical occupuncy elements. The simulated image shows no difference on the contrast for the normal and partical occupied elements. Does the code have this fuction. Thanks in advance.

**Comment by TomaSusi** [comment]
No, we do not support partial occupancy elements. The ASE/abTEM way to do this would be to edit the `Atoms` object.

**Comment by yc9690** [comment]
Thanks a lot for your very quickly replies. I planned to change the O occupancy to simulate STEM images to compare with the experiments. Actually, I get the supercell with ase basic function but it seems does not work when it is used for the abtem simulation.

**Comment by TomaSusi** [comment]
Yes, but _what_ in the experiment are you trying to compare to? Do you suspect the imaged specimen contains oxygen vacancies? In that case, the ASE/abTEM way is to delete atoms at random from the atoms object, run simulations, and average the results.

As for "get the supercell with ase basic function but it seems does not work" you'll need to provide the code you are trying as well as the error message if you want help on this. Thanks!

**Comment by yc9690** [comment]
Yes., I would like to see the oxygen vacancies contrast from the simulated images. From experimental ABF image, the O contrasts in some area are very low but is still visible. I would like to roughly quantify the O vacancies. That is why I want to compare it with simulation.

"In that case, the ASE/abTEM way is to delete atoms at random from the atoms object, run simulations, and average the results."  could you let me know how to delete atoms at random. The only way I know is manualy setting the occupancy in cif file and then simulate it. There is no error for running code. Just I cannot see the change of the contrast in the simulated images if I change occupancies.

**Comment by TomaSusi** [comment]
As we said, changing occupancies is not supported, so anything you do in the .cif file is ignored – the abTEM simulation does not include any partial occupancies and thus there should not be any change in the contrast.

Once you read in the file and create your `Atoms` object (which below I assume is named `atoms`), you can edit that within Python. To randomly delete `n` atoms of O, you could try this code (but please visualize the results to make sure they look reasonable):

```
import random

n = 1 # number of atoms to delete
O_indices = [atom.index for atom in atoms if atom.symbol == 'O']
O_to_delete = random.choice(O_indices, k=n)
del atoms[O_to_delete]
```

Just change `n` to be as many as you want.

**Comment by yc9690** [comment]
Thanks a lot for this available way. Do you know a simple way that I can specify the exact O columns to delete.

**Comment by TomaSusi** [comment]
You can use other conditions in selecting the indices, for example specifying a range of x, y coordinates, something like this:

`atoms[[atom.index for atom in atoms if atom.symbol=='O' && 2.0 < atom.position[0] <3.0 && 2.0 < atom.position[1] <3.0]]`

which would select atoms whose x and y coordinates are between 2.0 and 3.0.

Note that I did not test this code so the syntax might be a little off.
