### ISSUE TITLE
Issues on abtem-dask

### ISSUE THREAD

**Issue by wuyao3561** [abTEM/abTEM#78]
Hi Jacob, I have tried abtem-dask and it is great! But there are some issues when I tested it.
1. I always have problem: _AttributeError: 'NoneType' object has no attribute 'ifft2'_ when I use pyfftw, but when I use mkl_fft the problem is fixed;
2. I tried with prism_stem_stem_haadf_gpu and stem_haadf_gpu examples but face an out_of_memory_error. The CPU examples are good and the GPU version also work if the model is small (atom*=(3,3,3)) but it cannot work with a bit larger model (atom*=(5,5,5))

**Comment by wuyao3561** [comment]
Hi Jacob, I have solved this problem by reducing the 'chunks' value, but I was wondering what the largest model we could compute for the smallest chuncks (like chunks=1)?

I also notice some properties were changed for some objects, but I see some bugs after the change. for example, if I pre-define sigmas and pass it to frozen_phonon, I encounter problems of 'displacement standard deviation must be provided for all atomic species'. And I also cannot define the values like defocus, expansion_cutoff,Cs and ctf for the probe (or sMatrix).

Another problem is that in the abtem-master, we could save the hdf5 file through the save_file property in the detector but in dask version it cannot. 

As for now, the dask version is so great for its multi-gpu performance. i am trying to transfer some of my old abtem code to the dask version. looking forward that you could update the document so that we could know how to use the new version efficiently,

**Comment by wuyao3561** [comment]
oh i also have some problems when using the dask cluster. there is a warning:
` UserWarning: Cannot get CPU affinity for device with index 0, setting default affinity warnings.warn(distributed.preloading - INFO - Import preload module: dask_cuda.initialize`
if i run the code line by line it would not be a problem. but when i run the code directly using python command, this waring fully block the code from operation.

**Comment by jacobjma** [comment]
I am very happy that you are giving abtem-dask a try, it is essential to get feedback before we can merge this branch, so your questions are well-received. 

You have a lot of questions and some of them are not very specific, so it may take some time to address everything, but we will work our way through all of them.

It seems that you solved your first problems by installing mkl_fft. I addressed this in the main abtem-dask thread, this should be solved by providing a better error message and eventually by providing better documentation. But thank you for making me aware.

> I also notice some properties were changed for some objects, but I see some bugs after the change. for example, if I pre-define sigmas and pass it to frozen_phonon, I encounter problems of 'displacement standard deviation must be provided for all atomic species'. 

Thank you for reporting, I am not able to reproduce the issue based on the information you provided, could you provide code for reproducing this issue?

> And I also cannot define the values like defocus, expansion_cutoff,Cs and ctf for the probe (or sMatrix)

That is very surprising, again I can't reproduce. Can you provide code to demonstrate this?

> Another problem is that in the abtem-master, we could save the hdf5 file through the save_file property in the detector but in dask version it cannot.

We have decided to use zarr as the main format for abTEM because it works better with dask distributed. Is there a reason that you prefer hdf5? We are working hard to improve integration with hyperspy, so maybe you can use the ".to_hyperspy()" method and then use hyperspy to save the result to your favorite format.  

> I tried with prism_stem_stem_haadf_gpu and stem_haadf_gpu examples but face an out_of_memory_error. 

If this happens reproducibly, that is a major issue. I am _very_ surprised that you are running out of memory with stem_haadf_gpu.ipynb. What GPU are you using?

**Comment by wuyao3561** [comment]
Thank you Jacob for your quick reply!

> If this happens reproducibly, that is a major issue. I am very surprised that you are running out of memory with stem_haadf_gpu.ipynb. What GPU are you using?

In my own computer I only have a GTX1650 GPU with 4G storage so it is not that surprising lol. I tried chunk=100 and the stem_haadf_gpu.ipynb could work. But for prism_stem_stem_haadf_gpu.ipynb, if using the same setting with the stem_haadf_gpu.ipynb, I need to reduce chunks to 10 to avoid out_of_memorry problem. I have include the settings below. And I also notice the GPU memory was not released after the computation if I run it in jupyter notebook.

```python
chunks = 10

frozen_phonons = FrozenPhonons(atoms, 8, {'Si': .1})

potential = Potential(frozen_phonons, 
                      gpts=512,
                      projection='infinite', 
                      slice_thickness=2)

s_matrix = SMatrix(potential, energy=100e3, planewave_cutoff=20, chunks=chunks, interpolation=1, store_on_host=False)
scan = GridScan()

detectors = AnnularDetector(50, 150, ensemble_mean=True)

measurement = s_matrix.scan(scan=scan, detectors=detectors, distribute_scan=False, probes_per_reduction=1000, downsample='cutoff')
```

> And I also cannot define the values like defocus, expansion_cutoff,Cs and ctf for the probe (or sMatrix)
I found the traditional way of initializing sMatrix or Probe (shown as below) cannot be used in the dask version. And for this new version the semiangle_cutoff becomes planewave_cutoff, is there any difference between these two?
```python
probe = SMatrix(potential,
                energy=200e3,
                planewave_cutoff=21,
                expansion_cutoff=25,
                chunks=chunks,  
                rolloff=0.1,
                defocus=0,
                Cs=0,
                focal_spread=0,
                device=device)
```

>  for example, if I pre-define sigmas and pass it to frozen_phonon, I encounter problems of 'displacement standard deviation must be provided for all atomic species'.
Oh I figure out the reason. In the old version I could define sigmas for atoms that is not used in the computation. But in the dask version, if I have extra atoms in sigmas this error would happen.

> We have decided to use zarr as the main format for abTEM because it works better with dask distributed. Is there a reason that you prefer hdf5? We are working hard to improve integration with hyperspy, so maybe you can use the ".to_hyperspy()" method and then use hyperspy to save the result to your favorite format.
That is great. I would try the new hyperspy integration and I think it would be useful.

Thank you so much again for your reply! I would keep trying the new dask version and hope we could see the formal version soon.

**Comment by TomaSusi** [comment]
Dear @wuyao3561, is this issue still active for you?
