### ISSUE TITLE
plot probe phase and amplitude

### ISSUE THREAD

**Issue by smribet** [abTEM/abTEM#80]
Hi Jacob and Toma, 
I am working with some custom probes and interested in plotting both the phase and amplitude. It would be helpful to have a module for plotting (1) the phase of the probe and (2) the phase and the amplitude together based on color and intensity. I am happy to help contribute and would appreciate advice about how best this might fit in! 
Thanks,
Stephanie

**Comment by jacobjma** [comment]
Hi Stephanie,

It is actually possible to color complex images.

However, abTEM only plots "measurements", so it is necessary to make the wave function into a measurement. This was actually a bit annoying to do before (unless getting the intensity), so I just now added a quick `as_complex_image` method to the wave function object (only available in the development version).

```python
import numpy as np
from abtem import Probe

probe = Probe(energy=80e3, semiangle_cutoff=70, defocus=10, C12=15, phi12= np.pi/3, extent=10, sampling=.02)

probe.build().as_complex_image().show(figsize=(12,12), vmin=0, vmax=.35e-4, cbar=True);
```
![domain_coloring](https://user-images.githubusercontent.com/17334286/170647616-9e818a70-87fb-436f-ae9f-913281a454da.png)

I you feel like something needs to be improved (the colorbar certainly is not perfect); the relevant code is [here](https://github.com/jacobjma/abTEM/blob/263adcf45b5a612e9c3766287191e46bff451153/abtem/visualize/utils.py#L24) and [here](https://github.com/jacobjma/abTEM/blob/263adcf45b5a612e9c3766287191e46bff451153/abtem/visualize/mpl.py#L298) it uses the [HSLUV](https://www.hsluv.org/) colors which are [here](https://github.com/jacobjma/abTEM/blob/abtem-dask/abtem/visualize/colors.py).

**Comment by cophus** [comment]
This is awesome, thanks @jacobjma - if we need additional viz we can tweak what you have added here.

**Comment by smribet** [comment]
Yes, thank you so much! We are also interested in the complex CTF and realized while working with your example that its actually here `probe._evaluate_ctf()` but as an array not a measurement. 

I converted it back to a measurement like this to use your plotting function: 

```
CTF=np.fft.fftshift(probe._evaluate_ctf())
CTF_measure=abtem.Measurement(CTF,  abtem.measure.calibrations_from_grid(probe.gpts,
                                              probe.sampling,
                                              names=['alpha_x', 'alpha_y'],
                                              units='mrad',
                                              scale_factor=probe.wavelength * 1000,
                                              fourier_space=True))
CTF_measure.show()
```
I'm not sure this is the best way to do this - do you have a better suggestion? Would it be possible to add something like this as a method too?

**Comment by jacobjma** [comment]
Yes, you did it correctly. I think it is a good idea to have such a method, however, I added it to the `CTF` object.

Since the `CTF` does not have its own grid, this have to be provided:

```python
probe = Probe(energy=80e3, semiangle_cutoff=70, defocus=10, C12=15, phi12= np.pi/3, extent=10, sampling=.1)

probe.ctf.as_complex_image(probe.grid).show(cbar=True)
```
![ctf](https://user-images.githubusercontent.com/17334286/170962577-f47f3704-55b3-41ab-9bb2-a5623388eebf.png)

**Comment by smribet** [comment]
This is great! Thanks again!
