### ISSUE TITLE
phase flipping and phase shift in CTF

### ISSUE THREAD

**Issue by EthanJUCB** [abTEM/abTEM#83]
Hi Jacob and Toma,

I'd like to compare the CTF corrected experimental images with the abTEM simulated images which has the same phase flipped CTF applied. It seems like there is no function in the current CTF command. In addition, I wonder if it is possible to add phase shift to CTF in order to simulate the phase plate image.  Many thanks.

Best
Xi

**Comment by jacobjma** [comment]
It would have been somewhat difficult to do before, however, I just added an optional phase shift argument to the `CTF`. 

I think this should suffice?
```python
ctf1 = CTF(energy=200e3, defocus=100, phase_shift=0)
ctf2 = CTF(energy=200e3, defocus=100, phase_shift=np.pi)

fig, (ax1, ax2) = plt.subplots(1,2)
profiles = ctf1.show(reciprocal_units=True, ax=ax1)
profiles = ctf2.show(reciprocal_units=True, ax=ax2)
```
![phase_shift](https://user-images.githubusercontent.com/17334286/172367688-8e21b710-68d7-47fb-a58c-cc20c4dccbf6.png)

**Comment by EthanJUCB** [comment]
Hi Jacob,

The phase shift option looks great. I am going to give it a try.

Looking forward to the phase flipping option. 

Thanks very much.

**Comment by jacobjma** [comment]
Hi,

I thought that phase flipping was just shifting the phase by pi, which is done above. What is phase flipping if not that?

**Comment by EthanJUCB** [comment]
Hi Jacob,

Sorry for the really late reply. No, phase flipping refers to the flip of the negative part of CTF plots to positive. It would be great to have that in abTEM since it is the basic CTF correction.

**Comment by TomaSusi** [comment]
Could you provide an example in the published literature, or some good web resource?On 17.02.2023, at 04:18, Xi ***@***.***> wrote:﻿
Hi Jacob,
Sorry for the really late reply. No, phase flipping refers to the flip of the negative part of CTF plots to positive. It would be great to have that in abTEM since it is the basic CTF correction.

**Comment by EthanJUCB** [comment]
Hi Toma, 

Please see the paper from Downing and Gleaser, 
https://www.sciencedirect.com/science/article/pii/S0304399108000429?via%3Dihub
and this website http://www.bio.brandeis.edu/~shaikh/lab/ctf

It would be great to have the basic CTF corrections, such as phase flipping and Wiener filter, in abTEM.

**Comment by TomaSusi** [comment]
Thanks, that's helpful. Supporting phase flipping should be easy to do implement with a keyword.

Regarding Wiener filtering, this is applied to the image and not the CTF, right? You can apply any filter you'd like to the calculated image data, for example the SciPy implementation of the Wiener filter:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.wiener.html

**Comment by EthanJUCB** [comment]
Hi Toma,
That is great.
I am not sure how scipy handles that. To apply a Wiener filter, first we need to multiply the image by a CTF, then divid the sum of the squares of the CTF plus signal-to-noise ratio which varies. 
Please see the description of Wiener filtering, http://www.bio.brandeis.edu/~shaikh/lab/ctf and https://www.cryst.bbk.ac.uk/embo2019/ppts/Lec_05_EMBO_19-DKC-5.pdf

**Comment by TomaSusi** [comment]
Hi @EthanJUCB, sorry it's been taking so long but I have an initial implementation of the phase flipping, will try to do the Wigner as well before we merge:
https://github.com/abTEM/abTEM/pull/97

**Comment by EthanJUCB** [comment]
Many thanks Toma. That is very exciting. I wonder how to try that. 
I dowloaded this latest transfer.py in ctf_mods and replaced the old transfer.py in the main distribution. However, I had the error about "from abtem import stack" . Seems like there was no "stack" in the main distribution.

**Comment by TomaSusi** [comment]
Yes, all of this work is for the new abtem-dask branch, you'll need to use that. But I have not yet merged these changes, I am still doing some testing.

One question I have: looking at the formulas in the Downing article, it is not clear to me what ensures that the maximum values of the CTF remain 1 when applying SNRs that are lower than 1... but that is what figure 4 seems to show.

**Comment by TomaSusi** [comment]
If I add a normalization pre-factor of `(1 + 1/SNR)` then the behavior seems to match what is shown.

**Comment by TomaSusi** [comment]
```Cs = 10e-6 * 1e10  # 20 micrometers

ctf = abtem.CTF(Cs=Cs, energy=80e3)
ctf.defocus = ctf.scherzer_defocus # 79.14 A

aberration_coefficients = {"C10": -ctf.defocus, "C30": Cs}

ctf1 = abtem.CTF(aberration_coefficients=aberration_coefficients, energy=ctf.energy)
ctf2 = abtem.CTF(aberration_coefficients=aberration_coefficients, energy=ctf.energy, flip_phase=True)
ctf3 = abtem.CTF(aberration_coefficients=aberration_coefficients, energy=ctf.energy, wiener_snr=10)
ctf4 = abtem.CTF(aberration_coefficients=aberration_coefficients, energy=ctf.energy, wiener_snr=100)

fig, ax =  ctf1.profiles(max_angle=50).show(units="mrad")#, label = "CTF");
ctf2.profiles(max_angle=50).show(units="mrad", ax=ax)#, label = "CTF (phase flipped)");
ctf3.profiles(max_angle=50).show(units="mrad",ax=ax)#, label = "CTF (SNR=10)");
ctf4.profiles(max_angle=50).show(units="mrad",ax=ax)#, label = "CTF (SNR=100)");```

![download](https://user-images.githubusercontent.com/66075496/229107287-b66eae97-0fa3-4e1b-a014-ae13c7e4a43f.png)

**Comment by TomaSusi** [comment]
Okay, I think I got the filter working.

Am I correct to assume that for high values of SNR, the image wave will look very similar to the exit wave?

Is the filter supposed to conserve total intensity?

**Comment by TomaSusi** [comment]
Hi @EthanJUCB – the new features are now merged to the abtem-dask branch, you'll need to install this if you want to test it:

`pip install git+https://github.com/abtem/abtem@abtem-dask`

You can find the user documentation for this version, which will replace the current master branch soon, at:
https://abtem.github.io/doc/intro.html

The syntax for using phase flipping or the Wiener filter is given in my example above. Applying this to exit wavefunctions works exactly the same as before.
