### ISSUE TITLE
epie issue

### ISSUE THREAD

**Issue by Hansen311** [abTEM/abTEM#85]
Hi Jacob. I have tried the epie reconstruction using the examples in ./abtem/examples/reconstruction/epie.ipynb. However, there is a error in this script:
reconstructions_full = epie(band_limited_measurment, probe_guess, maxiter=3, return_iterations="True", fix_com="True")

The code is as same as in the examples, which is attahced. And the error given is as below:

File ~\AppData\Roaming\Python\Python39\site-packages\abtem\reconstruct.py:37, in _run_epie(object, probe, diffraction_patterns, positions, maxiter, alpha, beta, fix_probe, fix_com, return_iterations, seed)
     34     raise ValueError()
     36 if probe.shape != diffraction_patterns.shape[1:]:
---> 37     raise ValueError()
     39 if probe.shape != object.shape:
     40     raise ValueError()
<img width="815" alt="code" src="https://user-images.githubusercontent.com/103617284/178644149-903711ed-e621-4540-af43-17dc8ae92b10.png">
Thank you very much.

Jiake

**Comment by apater1** [comment]
I have the exact same issue. Any hints?

**Comment by jacobjma** [comment]
This was a bug, it should be fixed if you get the latest version from Github.

Thanks for the report.

**Comment by Hansen311** [comment]
Thank you.

**Comment by apater1** [comment]
Thank you for fixing it so fast.

Sincerely,
Anastasios
