### ISSUE TITLE
Adding noise to 4D-STEM diffraciton pattern

### ISSUE THREAD

**Issue by xiongh15** [abTEM/abTEM#90]
Dear jacobjma,
I am wondering if we can add noise to the 4D-STEM data to consider the effect of electron dose? Is it different from the noise function**(abtem.noise.poisson_noise)** provided in abtem aiming for images, not diffraction patterns?

Here I use abtem to generate 4D-STEM data set, which is used in Ptychography.

**Comment by jacobjma** [comment]
Hi,

You can use the `poisson_noise` function on diffraction patterns. It will use the scan calibration to calculate the "area per probe position", i.e. you should still provide the dose per area as if it was a HAADF image.

To be clear, applying poison noise to the 4D-STEM data, then applying an annular detector is equivalent to first applying the detector then applying the noise.

To be even more precise, given a 4d stem dataset from abTEM `measurement_4d`, the mean number of electrons `a` and `b` defined below will converge to "dose per area" times "scan area" as `num_samples` grows large.

```python
num_samples = 100
dose_per_area = 1e3

a = np.mean(
    [
        AnnularDetector(50, 200)
        .integrate(poisson_noise(measurement_4d, dose=dose_per_area))
        .array.sum()
        for i in range(num_samples)
    ]
)

b = np.mean(
    [
        poisson_noise(
            AnnularDetector(50, 200).integrate(measurement_4d), dose=dose_per_area
        ).array.sum()
        for i in range(num_samples)
    ]
)
```

**Comment by xiongh15** [comment]
Thanks so much for your quick reply! It helps A LOT! Now I know how to do it!  It helps A LOT!
