### ISSUE TITLE
TDS in CBED simulation

### ISSUE THREAD

**Issue by Shephardnihy** [abTEM/abTEM#94]
Following the TDS section in the walkthrough, I tried to simulate CBED pattern with 2 mrad convergence angle including TDS.

I created a potential object with class FrozenPhonons with 8 different configurations. When using PlaneWave, multislice simulation produces 8 diffraction patterns. However, using Probe only produce one diffraction pattern. The progressbar does not show TDS iteration progress.

I wonder if TDS is supported when using probe.multislice(pos, potential)?

Thank you.

**Comment by TomaSusi** [comment]
Hi @Shephardnihy!

You're using the master branch (or pip installation), right? So you are referring to this walkthrough?
https://abtem.readthedocs.io/en/latest/walkthrough/08_temperature.html

As you can see from the graphene example, frozen phonons should be supported with STEM as well. If you can share your code, I can have a look.

**Comment by Shephardnihy** [comment]
Thank you Toma!

I managed to include TDS in my CBED simulation following the walkthrough. Previously I was using `probe.multislice(position, potential)` and defines beam position explicitly, this seems to be not triggering the TDS. Following Scan and Detect helps me solve the issue. Thank you.

**Comment by TomaSusi** [comment]
Good to hear, thanks for reporting back in :)
