### ISSUE TITLE
Inconsistency between ctf.show() and exit_wave.apply_ctf(ctf)?

### ISSUE THREAD

**Issue by alouiset** [abTEM/abTEM#98]
Dear abTEM team,

I’m currently investigating the effect of off-axial aberrations on the phase contrast images of low dimensionnal materials (mostly graphene and carbon nanotubes). I am using the abTEM package to simulate exit wave intensities and also visualize CTF in 2D. Before starting my study, I was interested in comparing the results obtained via abTEM and the JEMS software to simulate HRTEM images of a single graphene layer.

First, when passing the same aberration coefficients (values and angles) both codes return the same CTF profiles along any particular direction (excluding small variations at high spatial frequencies). However, they return completely different exit wave intensities (using the function exit_wave.apply_ctf(ctf)). I noticed that, when diplaying 2D CTF images, CTF in abTEM were rotated at -90° relative to JEMS (90° clockwise). Note that I use my own functions to generate 2D CTF measurements, which are directly derived from the as_complex_image function in transfer.py. Doing so, I generate a measurement object I called: “ctf_2d”, using the self.evaluate_on_grid function. Then I can extract both the real and imaginary parts of the ctf_2d (get_real_ctf(ctf_2d) and get_imag_ctf(ctf_2d)), which can be visualized simply using the show_measurement_2d function: ctf_2d_real.show() and ctf_2d_imag.show().

```python
# Generate the abTEM grid object for 2D CTF
def generate_ctf_grid(ctf: CTF, grid_pts: int, max_spacial_freq: float) -> Grid:
    # Define grid sampling (in 1/Å)
    # Note: max_spacial_freq (in 1/nm)
    grid_sampling = 1/(2*max_spacial_freq/10)
    ctf_grid = Grid(extent=None, gpts=grid_pts, sampling=grid_sampling, dimensions=2)
    return ctf_grid
    
# Returns the Contrast transfer function as a complex image
def as_complex_image(ctf: CTF, grid: Grid, reciprocal_units: bool = True) -> Measurement:

    if reciprocal_units:
        # Set the 2D CTF representation in reciprocal space using reciprocal vector units
        calibrations = calibrations_from_grid(grid.gpts,
                                              grid.sampling,
                                              names=['k_x', 'k_y'],
                                              units='1/Å',
                                              scale_factor=1,
                                              fourier_space=True)
    else:
        # Set the 2D CTF representation in reciprocal space using scattering angle units
        calibrations = calibrations_from_grid(grid.gpts,
                                              grid.sampling,
                                              names=['alpha_x', 'alpha_y'],
                                              units='mrad',
                                              scale_factor=ctf.wavelength * 1000,
                                              fourier_space=True)

    array = np.fft.fftshift(ctf.evaluate_on_grid(grid.gpts, grid.extent))
    return Measurement(array, calibrations, name='2D CTF')

# Get the real component of the 2D CTF
def get_real_ctf(ctf_2d) -> Measurement:
    ctf_real = Measurement(np.real(ctf_2d.array), calibrations=ctf_2d.calibrations, units=ctf_2d.units, name=ctf_2d.name+' - real part', base_dimensions=ctf_2d.dimensions)
    return ctf_real

# Get the imaginary component of the 2D CTF
def get_imag_ctf(ctf_2d) -> Measurement:
    ctf_imag = Measurement(np.imag(ctf_2d.array), calibrations=ctf_2d.calibrations, units=ctf_2d.units, name=ctf_2d.name+' - imaginary part', base_dimensions=ctf_2d.dimensions)
    return ctf_imag
```

To obtain the same contrast in the simulated images, I had to modify aberration angle values (phi_nm) such as phi_abtem = -phi_jems + pi/2. This also returns the same CTF image as the JEMS calculation when calling ctf_2d_imag.show(). However, now the extracted CTF profiles (using ctf.show()) were different between JEMS and abTEM. The JEMS CTF profile along ky=0 and kx>0 is different from ctf.show(phi = 0). Naturally, this could be corrected by applying the same angle transformation : JEMS CTF profile along ky=0 and kx>0 is equal to ctf.show(phi = -0+np.pi)

At first, I though that this was due to a different angle convention used in abTEM and JEMS to define the aberration function. I looked at the documentation of both codes and it seems that the mathematical formalism is completely equivalent. I could not figure out why the angle values had to be different.

If I understood the abTEM code correctly, the data arrays inside Measurement objects are define such as the axis=0 of the np.ndarray(ndim=2) corresponds to the x axis of the actual 2D measurement (horizontal axis of the projected potential for example). This is different from the plt.imshow() convention where the x axis of an image corresponds to the axis=1 of the plotted np.ndarray(ndim=2). I guess this is why you introduced the np.swapaxes(array, 0, 1) operation in the show_measurement_2d function (mpl.py). I think this might be the source of an inconsistency between ctf.show() and exit_wave.apply_ctf(ctf).

Here’s what I obtained from the test I ran:

- JEMS comes with a default graphene supercell which I recreated in abTEM.

- I generated a potential object in abTEM where I imported the potential calculated by JEMS so both exit_wave intensities can be compared.

- I generated a strongly asymetric CTF, to compare the abTEM and JEMS calculations (with the same aberration angles passed to both codes).

- I extracted the CTF profiles at different phi angles: 0°, 90°, 180° and 270°. By hand for the JEMS one and using ctf.show(phi=…) for the abTEM one.

- The profiles are identical, excluding small variations at high spatial frequencies. I assume variations at high k values are due to my own user error and/or that JEMS computes silghty differently the envelope functions. In any case, this is not an issue to compare simulation results.

- Plotting the ctf_2d_imag.array directly using plt.imshow(), gives the same result as the JEMS calculation.

- However, plotting the ctf_2d_imag measurement via the show_measurement_2d function (ctf_2d_imag.show()) leads to a rotated CTF.

- Phase contrast simulated images are completely different.

- From there, I concluded that:

Calling the ctf.show(phi=phi) function calls the ctf.profiles() function which recalculates each time the profile along the “phi direction” and returns a 1D array. In this case, the calculated results is equivalent to the JEMS calculation by definition.

When generating the ctf_2d measurement using ctf.evaluate_on_grid(), the function ctf.evaluate and all parent functions down to evaluate_chi are called. This generates a np.ndarray(ndim=2) where the horizontal axis (x-axis of the “ctf image”) corresponds to the axis=1 of the np.ndarray. Therefore, simply plotting the ctf_2d_real.array (or ctf_2d_imag.array) gives a CTF representation consitent with the JEMS data. However, using the ctf_2d_real.show() (or ctf_2d_imag.show()) returns a transposed image because of the np.swapaxes(array, 0, 1) operation in the show_measurement_2d function.

In the same way, when calling the function exit_wave.apply_ctf(ctf), ctf.evaluate and parent functions are also called which generates a similar np.ndarray(ndim=2) where the horizontal axis (x-axis of the “ctf image”) corresponds to the axis=1 of the np.ndarray. This is where I think we face the inconsistency, when the function fft2_convolve is called. Because the exit_wave.array is contructed so its axis=0 corresponds at the x-axis of the image, it is like it gets convoluted with a transposed version of the originally desired CTF.

- The same ctf as JEMS is obtained simply using ctf_2d.array=np.transpose(ctf_2d.array). However, this solution will not resolve the phase contrast image issue.

- When changing the aberration angle values in abTEM such as phi_abtem = -phi_jems + pi/2, I was able to obtain the same contrast in both simulated images and the same CTF representation. Right now, this is the only solution I have to compare both results.

- This angle transformation is equivalent to a transposition (maybe with a flip of one of the axes, I’ll have to think about that) of the ctf_2d.array.

I am not sure if my explanation is right, but if it is, I guess some transposition of the ctf_2d array is necessary in the apply_ctf funtion (waves.py) as well as in the as_complex_image function (transfer.py), so ctf object axes are consistent with potential and wave object axes.

Maybe I misunderstood some key element of the code here. I tried to avoid it as much as I could and I hope my post is clear. I’ll be glad to discuss this issue in more detail with you. I provided you with some JEMS output txt files and my own test notebook so you can have a look. I am looking forward to hear from you because right now I am stuck.

Note: I'm using the last abTEM version: 1.0.0b32. You'll see at the end of the notebook that the calculated exit wave intensities are not exactly the same between abTEM and JEMS (even with the same input potential). This might be a discussion for later. 

Sorry for the way to long post…
Best regards,
Antonin Louiset.
[ctf_2d_hrtem_image_GitHub_issue.zip](https://github.com/abTEM/abTEM/files/11201928/ctf_2d_hrtem_image_GitHub_issue.zip)

**Comment by TomaSusi** [comment]
Thanks for the very detailed report! @jacobjma, could you have a look?

**Comment by alouiset** [comment]
Dear Toma and Jacob,

Did you had time to look at this issue? I look forward to hearing from you.

Best regards,
Antonin.

**Comment by jacobjma** [comment]
Dear @alouiset,

Sorry about not replying earlier, I must have missed it.

It seems that you are correct that there were an issue with the direction of assymetric aberrations. It should be fixed now.  When I run your notebook, the first comparison between abTEM and JEMS now looks quite identical (up to a small difference in contrast, as you note). 

Can you check that it works as you would expect by installing from the master branch? Then I will make a new release.

**Comment by jacobjma** [comment]
Dear @alouiset

Yes, they use the same code. Thanks again for making us aware of this issue. Please let us know if you find any other inconsistencies.

The new release includes these corrections, so I will close this now.

**Comment by alouiset** [comment]
Dear @jacobjma,
Thanks for the new release! I’ll inform my colleagues that the new version will probably break some previous codes. I’ll let you know if I encounter anymore troubles with abTEM.
Best regards.
