### ISSUE TITLE
HAADF atomic dots are quite small

### ISSUE THREAD

**Issue by lipai-ustc** [abTEM/abTEM#99]
Hi,
I'm a freshman in STEM simulation and thank you for sharing this useful package!
In my calculation, I always got ADF images with white dots much smaller than that usually observed in a real STEM images. I've tested the effect of vibration, but it doesn't change much. Can you help to locate the problem? Any other suggestion is also eagerly awaited.
The output image is like this:
![MoS2](https://user-images.githubusercontent.com/59822264/232937549-4a12e628-dbb9-4572-9297-1860a8ffe0b5.jpg)
My script is as follows:
```
import matplotlib.pyplot as plt
import numpy as np
from ase.io import read,write
from ase.lattice.hexagonal import Graphene
from ase.io import read,write
from abtem.structures import orthogonalize_cell
from abtem.visualize import show_atoms
from abtem import *
from abtem.transfer import scherzer_defocus

atoms=read("MoS2.vasp")

atoms.center()
alpha=21.5
E=200e3
Csval=3e5
df=scherzer_defocus(E, Csval)
df=30
print("defocus: ",df)

potential = Potential(atoms, sampling=.04)

bf_detector = AnnularDetector(inner=0, outer=alpha/2)
adf_detector = AnnularDetector(inner=alpha*4, outer=alpha*8)
detector=[bf_detector,adf_detector]
#detector=adf_detector

gridscan = GridScan(start=[0, 0], end=[atoms.cell[0][0], atoms.cell[1][1]], sampling=.2)

S = SMatrix(expansion_cutoff=28,
            interpolation=3,
            energy=E,
            semiangle_cutoff=28,
            defocus=df)

measurements_iam = S.scan(gridscan, detector, potential)

bf_iam = measurements_iam[0].interpolate(0.04).tile((1,1))
adf_iam = measurements_iam[1].interpolate(0.04).tile((1,1))
#adf_iam = measurements_iam.tile((2,3)).interpolate(0.04)

from matplotlib import pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(10,5), gridspec_kw={'hspace': 0.5, 'wspace': 0.1})
adf_iam.show(ax=axes[0], equal_ticks=True,scale=1.1)
axes[0].set_title('(a) ADF (IAM)', x=0, ha='left')
bf_iam.show(ax=axes[1], equal_ticks=True)
axes[1].set_title('(b) BF (IAM)', x=0, ha='left')
plt.savefig('MoS2.jpg',dpi=300)
```

**Comment by TomaSusi** [comment]
Hi @lipai-ustc,

Your simulation is quite ideal, with a Cs of only 30 µm (so essentially perfect aberration correct), no other aberrations, and no decoherence. In such idealized conditions you can seen the Airy rings, which is certainly not very realistic.

A finite source size would be a realistic source of decoherence that tends to blur your images; this can be treated accurately physically in the Dask version of abTEM, but you can also just apply a Gaussian blur the emulate the same effect:
https://abtem.github.io/doc/user_guide/tutorials/partial_coherence.html

Alternatively, you could try applying frozen-phonon images to blur the atomic contrast.

Cheers,
Toma

**Comment by lipai-ustc** [comment]
Hi Toma,

Thank you for your reply and the information. I'd like to use the partial coherence method as described in the link you provided. It seems the abtem version in the document is different from the newest version in github, and some functions are missing. can you provide more guidance on how to realize this method using the current version?

best,
Pai LI

**Comment by TomaSusi** [comment]
Ah sorry, this was indeed for the upcoming Dask update. We have most of this functionality also in the current version:
https://abtem.readthedocs.io/en/latest/walkthrough/05_contrast_transfer_function.html#Partial-coherence
